- Cargo.lock
- shell.nix
- theseus/Cargo.toml
- theseus/examples/download-pack.rs
- theseus/src/lib.rs
- theseus/src/modpack/manifest.rs
- theseus/src/modpack/mod.rs
This PR adds support for downloading, extracting, and expanding modpacks. Additonally, it adds example and test code for the use of this module. The code (should) be compliant with the Modrinth modpack specification and be ready to handle launcher support for versioned modloaders and storage of metadata packaged with the manifest.
> Add modpack support

- Cargo.lock
- theseus/Cargo.toml
- theseus/examples/download-pack.rs
- theseus/src/launcher/mod.rs
- theseus/src/modpack/manifest.rs
- theseus/src/modpack/mod.rs
- theseus/src/modpack/modrinth_api.rs
- theseus/src/modpack/pack.rs
This PR adds in support for modpack creation and management:
> Add modpack creation

- .idea/prettier.xml
- theseus_gui/package.json
- theseus_gui/pnpm-lock.yaml
- theseus_gui/src/routes/index.svelte
Switches from `lsof` to the package `kill-port-process` for killing the sveltekit dev process when tauri exits.
> Fix GUI dev command on Windows

- theseus_gui/README.md
- theseus_gui/package.json
The `pnpm dev` command used to always try to kill the SvelteKit process, because of tauri-apps/tauri#2794, but that bug doesn't always happen, so the process killing has been moved to the `pnpm kill:web` command. See the readme:
> If after quitting the dev process, you find that the SvelteKit process is still running (or preventing you from restarting the dev command), run `pnpm kill:dev`
> Fix GUI dev command (by not trying to kill the process)

- Cargo.lock
- theseus/Cargo.toml
- theseus/src/util/jre.rs
- theseus/src/util/mod.rs
Added JRE detection using function get_all_jre(), which returns a vec of _unique_ JavaVersions with all symlinks resolved. 
FIxes MOD-309
> Jre detection

- Cargo.lock
- theseus/Cargo.toml
- theseus/src/api/pack.rs
- theseus/src/api/profile_create.rs
- theseus/src/error.rs
- theseus/src/state/projects.rs
- theseus_playground/src/main.rs
- changes most uses of ZipArchive to use async_zip crate instead
- crate::Result now has Send and Sync again,  which fixes Tauri problem
> Tauri errors fix

- theseus/src/state/tags.rs
- theseus_gui/.gitignore
- theseus_gui/dist/.gitignore
Fixes a major issue where a stack overflow happens on only Win10 devices (not mac, linux) running tauri calling the tag api.
Restructured so that json decodes arent happening simultaneously (which is probably what was causing it- just hit some space limit)
> fixed win10 stack overflow

- .cargo/config.toml
- added config.toml for windows specific compilation (increases stack size)
> Windows compile opts

- theseus_gui/src-tauri/src/api/settings.rs
Now java args can be get/set as a string, where they are split by a space in the transition from the back and front end
> added frontendsettings

- theseus_gui/src-tauri/Cargo.toml
- theseus_gui/src-tauri/tauri.conf.json
- theseus_gui/src/App.vue
- theseus_gui/src/assets/icons/index.js
- theseus_gui/src/assets/icons/log-in.svg
- theseus_gui/src/assets/stylesheets/global.scss
- theseus_gui/src/components/ui/AccountsCard.vue
- theseus_gui/src/components/ui/Instance.vue
> MC Authentication + Account switching

- theseus/src/event/emit.rs
- theseus/src/state/mod.rs
- theseus/src/state/tags.rs
- Fixes stack overflow issue when running a new profile
> fixes stack overflow :)

- theseus_gui/src-tauri/tauri.conf.json
This fixes launcher pages being blocked by some system webview implementations.
Requires https://github.com/modrinth/knossos/pull/1106 and https://github.com/modrinth/omorphia/pull/41 to be merged first or images and videos on mod pages will not load.
> Update tauri content security policy

- theseus/src/util/jre.rs
- JRE checker was not quite hitting all the folders listed for linux. It was searching for X/Y rather than X/{any folder}/Y
> linux jre missing folders

- .vscode/launch.json
- .vscode/tasks.json
- theseus/src/api/profile.rs
- theseus/src/state/mod.rs
- theseus/src/state/projects.rs
- Adds tauri compliant debugger so we can do a full debugging process
- Pins several high-stack function async functions to reduce stack load
> debugging; box pinning

- theseus_gui/src/App.vue
- theseus_gui/src/components/modrinth-loading-indicator.js
- theseus_gui/src/pages/AddInstance.vue
- theseus_gui/src/pages/Index.vue
- theseus_gui/src/pages/project/Index.vue
- theseus_gui/src/store/loading.js
- theseus_gui/src/store/state.js
> Loading bars

- theseus/src/api/profile.rs
- theseus/src/state/profiles.rs
- theseus/src/state/projects.rs
- theseus_gui/src-tauri/src/api/profile.rs
- theseus_gui/src/components/ui/Instance.vue
- theseus_gui/src/pages/Browse.vue
- theseus_gui/src/pages/Settings.vue
- theseus_gui/src/pages/instance/Index.vue
- theseus_gui/src/pages/instance/Mods.vue
> Profile mods page

- COPYING.md
The COPYING.md file had a reference to knossos and its license, AGPL, carried over from that project. This PR corrects that to the current theseus license.
> Adjust COPYING for Theseus

- theseus_gui/src-tauri/src/api/utils.rs
Resolves #188
We already use `xdg-open` to open paths with `,` so why not use it for normal paths too?
When attempting to open the profile's folder, I encountered some issues. In some cases, the file explorer would open but display an error message “Method not supported,” or it would indicate that the library needed for `dbus` was not found. 
I tested my changes on both AppImage and `tauri dev`.
IDK! It works correctly on my computer, It looks like it doesn't have some envs. I didn't change anything that might interrupt that.
> Fix correctly show in folder

- theseus_gui/src/components/ui/AccountsCard.vue
Bump account-card `z-index` to 11 (from 9) to fix issue with badges on the homepage being displayed above it. Also add a `max-height` and `overflow-y` to the account-card class, so that users with a large amount of accounts can view all accounts properly. 
Related to this [message](https://discord.com/channels/734077874708938864/1120929730863050873/1140236231217778778) on the Modrinth Discord.
> Fix z-index and add scrolling for AccountsCard

- theseus_gui/src/components/ui/ContextMenu.vue
- theseus_gui/src/components/ui/ModInstallModal.vue
- theseus_gui/src/pages/instance/Mods.vue
Disabled all buttons that have actions on mods except share actions when the instance is still paired to a modpack. Every single disabled button includes a tooltip that has text similar to this: "Unpair this instance to update mods". Also added a message to the mod install modal to let the user know that they cannot add mods to a paired instance. 
Had to wrap all disabled elements in an extra div because the root element is disabled and from my testing disabled elements don't allow tooltips.
Fixes #625
> Fix being able to add mods to paired instances

- theseus_gui/src-tauri/tauri.conf.json
Added youtube to the list of allowed sources for iframes. CSP doesn't seem to apply to dev builds so the bug was only present in production builds. 
fixes #223
> Update CSP to allow youtube embeds

- theseus_gui/src-tauri/tauri.conf.json
Allow `https://api.mclo.gs` in the Tauri CSP so that users can share their logs. Fixes the "Failed to fetch (https://api.mclo.gs/1/log)" error.
> Update CSP to allow mclo.gs

- theseus_gui/src/components/ui/Instance.vue
- theseus_gui/src/components/ui/InstanceCreationModal.vue
- theseus_gui/src/pages/Browse.vue
- theseus_gui/src/pages/Settings.vue
- theseus_gui/src/pages/instance/Index.vue
- theseus_gui/src/pages/instance/Logs.vue
- theseus_gui/src/pages/instance/Options.vue
- theseus_gui/src/pages/project/Index.vue
1. Added a limit for the instance name in the breadcrumbs, so that a very long (~50char) instance name doesn't push aside the other elements, making exiting the application impossible. Fixed overflow in mod browse. Fixes #740 
3. Added a limit of 100 characters in the instance creation modal, there is no reason for an instance's name to be longer.
4. Fixed log viewing options overflowing with a small window, now they are scrollable.
5. Increased instance avatar size from `sm` to `lg` in the library so that the gray corners in icons are less visible.
6. Fixed and rounded the white corner in the log viewer.
7. Increase step to 64 for memory related inputs for a more consistent and comfortable experience.
8. Fix instances imported from an mrpack file throwing an error (making it impossible …
> Overflow and mrpack fixes, comfortable memory slider and more.

- theseus_gui/src/components/ui/ModInstallModal.vue
Change some lines in the mod install modal to allow adding mods to unlocked instances, also changed the disabled tooltip to mention unlocking an instance to add mods.
Fixes #746
> Allow mods to be added to unlocked instances.

- .github/ISSUE_TEMPLATE/bug_report.yml
The label was added to the parent tag `attributes` instead of being added inside it to the `label` tag,
First commit was test to fix the issue while not seeing the real issue (reverted in second commit)
> Fixing bug report template - Wrong nesting

- theseus/src/api/pack/install_from.rs
Fixes #772. Stays backwards compatible in case any packs were produced locally with the old serialization.
> Use 'neoforge' instead of 'neo-forge' in mrpacks [MOD-539]

- .github/workflows/tauri-build.yml
- theseus/src/api/pack/install_from.rs
- theseus/src/api/pack/install_mrpack.rs
- theseus/src/api/profile/mod.rs
- theseus/src/lib.rs
- theseus/src/state/mod.rs
- theseus/src/state/profiles.rs
- theseus/src/state/projects.rs
- theseus_gui/src-tauri/src/api/profile.rs
- theseus_gui/src/components/ui/ExportModal.vue
- theseus_gui/src/helpers/profile.js
Fixes #754
There was previously a difference between Windows and the other platforms. It would appear that you could deselect exporting of mods during modpack export on Windows, while Linux and Mac wouldn't get those options. Now all platforms have the option to deselect exporting of mods/shaderpacks/whatever and it works as expected.
> Make export selection consistent between platforms and allow selecting which projects to export

- theseus/src/error.rs
- theseus/src/state/profiles.rs
This addresses an issue brought to our attention by the modpack "Mimi Adventure", with the following repro steps, using version 0.6.0 of the app on Windows:
1. Create a profile using the modpack "Mimi Adventure" (https://modrinth.com/modpack/mimi-adventure)
2. Unpair the profile
3. Launch minecraft
4. Export the modpack with the "pfm" folder included as an override.
This produces the following error:
```
Filesystem error: Path "\\\\?\\C:\\Users\\USER\\AppData\\Roaming\\com.modrinth.theseus\\profiles\\Mimi\\pfm\\cache\\resources\\assets\\pfm\\models\\block\\chair_classic\\stripped_luphie_flowering_pink_luphieclutteredmod_chair_classic\\stripped_luphie_flowering_pink_luphieclutteredmod_chair_classic_tucked.json" does not correspond to a profile
```
This error occurs because the path length …
> Fix handling of paths longer than 260 chars on Windows during export

- theseus_gui/src/components/ui/AccountsCard.vue
Switches from [mc-heads.net](https://mc-heads.net/) to [Crafatar](https://crafatar.com/).
Main reason is caching, mc-heads caches for around 6 hours or so, but Crafatar updates their caches every 20 minutes, this means that any person changing a skin will have their changes be visible much faster. Crafatar is also used by Hypixel, Mineplex, The Hive and NameMC, so it is as battle-tested if not more so than mc-heads.
> Update avatar URLs to use Crafatar API.

- theseus_gui/src/pages/instance/Options.vue
This PR changes the fullscreen option in instance to be a toggle instead of a checkbox so it is more consistent
now:
PR:
> change instance fullscreen-checkbox to toggle

- theseus_gui/src/components/RowDisplay.vue
This PR fixes a weird behavior that sometimes causes too many projects to be displayed
reason why this happened:
the `onMount` hock renders the page and then gets called which in most cases results in the container element in which the projects are rendered to be the correct width without any projects being inside them.
There is just the edge case where the height of the projects adds a scrollbar on the side which changes the width of the container without triggering a resize.
this PR fixes this by always rendering one element which forces a scrollbar to be rendered before `onMount`
> fix rendering/calculation of maxProjectsPerRow in homepage

- theseus_gui/src/helpers/profile.js
Fixed bug when creating instance starting or ending with spaces has errors
Based on issue #765 & #808
> Project without space

- theseus_gui/src/components/ui/AccountsCard.vue
- theseus_gui/src/pages/instance/Mods.vue
The bug was caused by the page number staying the same even when there are fewer number of pages. I fixed this by setting the page to 1 when a new search is performed.
Fixes #798
> Search pagination fix

- theseus/src/api/hydra/init.rs
- theseus/src/api/hydra/refresh.rs
- theseus/src/api/hydra/stages/bearer_token.rs
- theseus/src/api/hydra/stages/mod.rs
- theseus/src/api/hydra/stages/player_info.rs
- theseus/src/api/hydra/stages/poll_response.rs
- theseus/src/api/hydra/stages/xbl_signin.rs
- theseus/src/api/hydra/stages/xsts_token.rs
- theseus/src/api/logs.rs
- theseus/src/launcher/mod.rs
- theseus/src/state/children.rs
- theseus/src/state/dirs.rs
- theseus_gui/src-tauri/src/api/logs.rs
- theseus_gui/src/App.vue
- theseus_gui/src/components/ui/AccountsCard.vue
- theseus_gui/src/helpers/logs.js
- theseus_gui/src/helpers/profile.js
- theseus_gui/src/pages/Settings.vue
- theseus_gui/src/pages/instance/Logs.vue
- theseus_gui/src/pages/instance/Mods.vue
- auth routes now are called 3 times before failing, taking the last failure as the returned failure
- added stdlog trakcing again, for instances, and a new pair of logs in the logger that shows them (in some cases, they will differ from latest.log)
> Auth retrying, std logs

- theseus_gui/src/components/ui/AccountsCard.vue
- theseus_gui/src/components/ui/tutorial/LoginCard.vue
This PR fixes the missing `:noblur` from various login modals, making it so that users with no advanced rendering still get the blurry background.
Closes #713
> Add missing noblur value to modals.

- theseus_gui/src/pages/project/Versions.vue
Wrap the text inside project names to reflect the behavior on the website.
Closes #908
> Add text wrapping to project version names.

- theseus/src/api/pack/import/curseforge.rs
currently importing a CF profile uses the manifest.json file to get the modloader. but this file does not exist for custom profiles (but only for premade modpacks).
getting the required info from minecraftinstance.json instead makes it possible to also import custom profiles from CF.
fixes #913 and #874
ill mark it as a draft for now because i still want to do some testing to make sure that minecraftinstance.json is reliable for all modloaders
> fix custom profile import for CF

- theseus/src/launcher/args.rs
Removes the *seemingly* unnecessary lwjgl debugging argument added in https://github.com/modrinth/theseus/pull/98/commits/c6ff655422ceadce11893c09685cb10f70effb10.
Resolves https://github.com/modrinth/theseus/issues/947.
> Remove lwjgl debugging argument.

- theseus/src/state/mr_auth.rs
Refresh is not saving credentials to file- resulting in auth.json file no longer matching session stored in db (as refresh call to the labrinth API modifies the token)
This error doesn't get printed to the console because it doesnt tell you if the refresh failed unless the refresh failed AND your current token's locally cached expiry date hasnt expired yet. So on the second or third boot-up, you are out of sync and theres no message printed until the token expires naturally
> adds credentials refresh save

- theseus/src/util/io.rs
Fixes #1050 
As far as I can tell, the original Tauri call simply wraps the Tokio call. By using Tokio directly, we remove the `theseus` dependency upon Tauri.
> Use Tokio directly instead of Tauri in io.rs

- theseus/src/api/pack/install_mrpack.rs
Closes #1112
According to the [docs](https://support.modrinth.com/en/articles/8802351-modrinth-modpack-format-mrpack#h_3ad1b429f0), it needs to be `client-overrides`, not `client_overrides`. This PR fixes this typo.
> Fix `client-overrides` not getting extracted

- theseus_gui/src/components/ui/ErrorModal.vue
Many people contacting support forget to provide the debug information,
which significantly delays the resolution time because we're forced to
ask for this information anyway, as without it we cannot tell with
certainty the issue the person is facing.
Ideally in the future it would probably make sense to give a link to the
article describing the common issues for self-help, but there's no such
article yet. Perseus however is able to give suggestion for a few issues
given that it has the debug information.
> Prompt users to provide debug info to support

- theseus_gui/src-tauri/tauri.conf.json
Issue #1175 
Some references from Apple's Website:
https://support.apple.com/en-en/105118
https://forums.developer.apple.com/forums/thread/739387
> Changed app category to “Game” to enable GameMode on macOS Sonoma 14+

- apps/app/src/pages/Browse.vue
- apps/app/src/routes.js
**Note: PR #1232 has been reopened following the switch to a monorepo organization.**
This PR fixes an issue where Vue's scrolling behaviour inconsistently failed to scroll to the top of the entire page on certain desktop environments or operating systems. The problem occurred because Theseus has scrolling within an inner container rather than the entire page, leading to inconsistent behaviour.
> Theseus: Fix scrolling to top problems

- apps/frontend/nuxt.config.ts
- apps/frontend/src/components/ui/Badge.vue
- apps/frontend/src/components/ui/NotificationItem.vue
- apps/frontend/src/components/ui/ProjectCard.vue
- apps/frontend/src/layouts/default.vue
- apps/frontend/src/pages/[type]/[id].vue
- apps/frontend/src/pages/dashboard/collections.vue
- apps/frontend/src/pages/dashboard/index.vue
- apps/frontend/src/pages/dashboard/notifications.vue
- apps/frontend/src/pages/dashboard/organizations.vue
- apps/frontend/src/pages/dashboard/projects.vue
- apps/frontend/src/pages/dashboard/reports.vue
- apps/frontend/src/pages/dashboard/revenue/index.vue
- apps/frontend/src/pages/settings/account.vue
- apps/frontend/src/pages/settings/applications.vue
- apps/frontend/src/pages/settings/authorizations.vue
- apps/frontend/src/pages/settings/index.vue
- apps/frontend/src/pages/settings/language.vue
- apps/frontend/src/pages/settings/pats.vue
- apps/frontend/src/pages/settings/profile.vue
- apps/frontend/src/pages/settings/sessions.vue
- apps/frontend/tailwind.config.js
- packages/assets/icons/scale.svg
- Corrects the Tailwind config not targeting the /src folder 
- Explicitly defines styles for elements that previously inherited styles from the browser, but were reset by Tailwind
- Fixes mobile footer alignment
- Sets the slug to `code` in Nuxt config
- Removes `modrinth/knossos` in the footer to reflect the change to a monorepo
> Frontend Tailwind Fixes + Small Fixes 

- apps/frontend/package.json
- pnpm-lock.yaml
This fixes the issue where types for `NuxtApp` would be incorrect due to the incorrect `Plugin` return type by `@vintl/nuxt`.
> Update @vintl/nuxt to ^1.9.2

- README.md
This problem was mentioned in #2140. Discord link in footer works correctly for me.
> fix: Correct discord link in `README.md`

- apps/frontend/src/assets/styles/components.scss
Closes: #2179 
Removes the auto margin property from the inner svg inside of square-button classes.
Member list:
Member list:
Publishing list:
I've tested this by navigating to other pages where the square button is used and verified it still looks okay.
> fix(knossos): remove auto margin from square button svg

- apps/frontend/src/pages/search/[searchProjectType].vue
Previously, the Exclude button was removed from the the element tree
entirely until the group is hovered. Only when the group is hovered, the
button element was being switched to a proper display form. This has
caused the layout shift which was very visible when quickly moving
cursor over the filter options.
This commit makes it so that the Exclude button is always in its proper
display form (flex), however is transparent until the group is hovered.
The repeated transparency classes were removed from the icon as well to
prevent jarringly-looking double transition.
> Remove shift caused by the Exclude filter button

- apps/frontend/src/pages/[type]/[id]/version/[version].vue
There is a bug in vue-multiselect library where it will default
`custom-label` property to raw properies object. Presumably this is a
bug that appeared because they ported library to Vue 3 and have not
considered that the signature for `default` prop's function has changed.
To work around this, we can provide custom `custom-label` property that
is just a function that returns the input itself. In other places, where
objects are passed, `label` property can be used. In this case the first
suggestion applies. DO NOT USE VUE-MULTISELECT WITOUT `LABEL` OR
`CUSTOM-LABEL` PROPS!
Fixes #2293
Fixes #2343
> Fix Game versions input not showing

- apps/app-frontend/.eslintrc.cjs
- apps/app-frontend/eslint.config.mjs
- apps/app-frontend/package.json
- apps/app-frontend/src/components/ui/AccountsCard.vue
- apps/app-frontend/src/components/ui/InstanceCreationModal.vue
- apps/app-frontend/src/components/ui/JavaSelector.vue
- apps/app-frontend/src/components/ui/SplashScreen.vue
- apps/app-frontend/src/components/ui/install_flow/IncompatibilityWarningModal.vue
- apps/app-frontend/src/components/ui/install_flow/InstallConfirmModal.vue
- apps/app-frontend/src/components/ui/install_flow/ModInstallModal.vue
- apps/app-frontend/src/helpers/utils.js
- apps/app-frontend/src/pages/Browse.vue
- apps/app-frontend/src/pages/Index.vue
- apps/app-frontend/src/pages/Settings.vue
- apps/app-frontend/src/pages/instance/Logs.vue
- apps/app-frontend/src/pages/instance/Mods.vue
- apps/app-frontend/src/pages/instance/Options.vue
- apps/app-frontend/src/pages/project/Gallery.vue
- apps/app-frontend/src/pages/project/Index.vue
- apps/app-frontend/tsconfig.app.json
- apps/app-frontend/tsconfig.json
- apps/app-frontend/tsconfig.node.json
- pnpm-lock.yaml
An alternative take on #2286
- Uses TSConfigs from the official Vite template
I think these are extensively tested and match Vite's behavior better.
- Adds `vue-tsc` for proper type checking in Vue files
- Switches to ESLint 9 and Nuxt config
Nuxt ESLint config is a pretty good starter, even for non-Nuxt projects. If there are some Nuxt-related rules, they can be simply overriden. In the future I think it would make sense to instead push it and and our overrides to `eslint-config-custom` package to share between other packages as well.
> Add TypeScript to app-frontend

- Cargo.lock
- apps/app-frontend/package.json
- apps/app-frontend/src/components/ui/AddContentButton.vue
- apps/app-frontend/src/components/ui/InstanceCreationModal.vue
- apps/app-frontend/src/components/ui/JavaSelector.vue
- apps/app-frontend/src/components/ui/install_flow/ModInstallModal.vue
- apps/app-frontend/src/pages/instance/Options.vue
- apps/app/Cargo.toml
- apps/app/src/api/ads.rs
- apps/app/tauri.conf.json
- packages/app-lib/Cargo.toml
Fixes issues where icon can't be set or mods can't be added to profiles from files
> Fix file paths opening on app

- apps/app/src/main.rs
- apps/labrinth/README.md
- apps/labrinth/src/queue/moderation.rs
- apps/labrinth/src/routes/mod.rs
- packages/ui/src/components/base/MarkdownEditor.vue
- Markdown guide link to support article
- API version deprecated error to new docs
- Modpack permissions error to support article
- Labrinth README links to new docs
- App WebView2 link to support article
- Cheery-pick to new branch
> fix: update old docs links

- apps/docs/astro.config.mjs
Starlight defaults to favicon.svg, however a favicon.ico was added to the repo.
Changes:
- Format astro config according to Prettier
- Properly set favicon path
> fix(docs): correct favicon url

- apps/frontend/src/components/ui/ProjectMemberHeader.vue
CSS one-liner that fixes the lack of a top margin on the author actions section when creating a new project.
See below for a before and after:
> Fix top margin issue for author actions section

- apps/frontend/src/pages/servers/manage/[id]/options/loader.vue
standalone versions (ie 1.21, 1.20, 1.19 etc) didn't show up before. this fixes that
> fix(servers): standalone versions not showing up in loader page

- apps/frontend/src/composables/auth.js
Resolves an issue where the frontend generated URLs without provider property when there is a frontend redirect uri. Without the provider, labrinth defaults to GitHub. My fix is shitty, but I didn't want to bother with URL encoding.
Fixes #2884
> fix(frontend): generate auth URL with provider

- apps/frontend/src/components/ui/charts/ChartDisplay.vue
Resolves #2400 by removing the SVG suffix.
> fix(frontend): remove double dollar sign in chart

- apps/frontend/src/pages/user/[id].vue
Shows and formats the date when the user joined, on hover. Stole the code from version date rendering. Can add `cursor-help` if wanted.
Resolves #2243
> feat(frontend): show date of user join

- apps/frontend/src/pages/servers/index.vue
- Make FAQ headings medium instead of bold to differentiate question text from the FAQ card header
- Add Miami location for new node
- Make plan buttons just say 'Get started' instead of login
- Add query string support for plans, which is also utilised when a user is logged out so the purchase modal auto-opens once logged in with their plan
- Add card about how servers aren't over-allocated, linking to the new Pyro status page
> feat(marketing): miami, overallocation card, misc fixes

- apps/frontend/src/pages/search/[searchProjectType].vue
Replaces the substring operation to find project type with a regex. The regex is a bit complex, so I added a comment explaining it.
Resolves #1382
> fix(frontend): project search page with trailing slash

- apps/frontend/src/pages/[type]/[id].vue
- apps/frontend/src/pages/[type]/[id]/version/[version].vue
- apps/frontend/src/pages/[type]/[id]/versions.vue
- apps/frontend/src/pages/user/[id].vue
Hides the report button from your own projects, versions, and user. There might be some still showing in the app, but I am not comfortable developing for it yet.
Places updated:
- Project view overflow menu
- Version list overflow menu
- Version view
- User view
Resolves #1381
> fix(frontend): hide report button on own projects

- apps/labrinth/src/routes/internal/flows.rs
Fixes #2875 by using totp-rs's method for checking validity, which accounts for the configured skew. The standard recommends a value of one period of skew, which is what we are configured to support. This was however not supported because of how the TOTP was checked.
> feat(labrinth): totp skew

- apps/labrinth/src/routes/internal/pats.rs
Uses the macros provided by validator to validate the name. The name already had a macro, but `.validate()` was not called. Stole the snippet from PAT creation route.
Resolves #1549
> fix(labrinth): validate PAT name

- apps/frontend/src/layouts/default.vue
`route.name` isn't necessarily defined, so this may cause an exception leading to 500 internal server error.
Resolves #2989
> fix(frontend): internal server error on 404

- .github/ISSUE_TEMPLATE/2-web-bug.yml
- .github/ISSUE_TEMPLATE/3-api-bug.yml
The issue labels seem to have been renamed without updating the issue templates, resulting in those labels not being applied.
`api` → `backend`
`frontend` → `web`
> fix: issue templates used outdated label names

- apps/frontend/src/pages/search/[searchProjectType].vue
Only one element should have the same id. The id is used to link with the label's `for` attribute. There may be similar issues other places, but this is the one that was brought to my attention.
Resolves #2999
> fix(frontend): remove duplicate id for searchbars

- apps/app-frontend/src/components/ui/SearchCard.vue
- packages/assets/icons/spinner.svg
- packages/assets/index.ts
- packages/assets/styles/variables.scss
Added indicator for project installation in search in the app, regardless of hover state.
> Project installation indicator

- apps/frontend/src/pages/dashboard/collections.vue
When searching for collections, the casing will normally be ignored. The item for "Followed Projects" will be removed if using capitalized characters though. This is especially confusing since it's titled with partially capital letters.
Resolves modrinth/code#1370
> fix(frontend): ignore case in collection search for followed

- apps/frontend/src/pages/servers/manage/[id]/content/index.vue
The "Change platform" Button on a Vanilla Server, currently leads to the wrong page, this PR fixes it to instead redirect to the Choose Loader page in the Options
> fix: Change platform button leads to wrong page

- apps/frontend/src/components/ui/servers/BackupSettingsModal.vue
- apps/frontend/src/components/ui/servers/TeleportDropdownMenu.vue
- Replaced hours input with a dropdown menu
- Fixed 'Save Changes' button: now disables properly when no changes are made and auto-backups are off
- Servers dropdown component: added rounded corners to the last elements for consistency
> fix(server backup settings): number input -> dropdown

- packages/app-lib/src/api/pack/install_mrpack.rs
- packages/app-lib/src/state/cache.rs
- packages/app-lib/src/state/legacy_converter.rs
- packages/app-lib/src/state/profiles.rs
This works by ignoring the profile loader for the non-mods and instead using a set of loaders defined by the file type.
Fixes #1057
> Make the update checker work for non-mods

- apps/frontend/src/pages/[type]/[id]/version/[version].vue
When using `version/latest` with filters that lead to no mod version the page will result in an error page, due to an exception when trying to reduce an empty array, this adds a 404 page when no version is found matching the filters
Example: https://modrinth.com/mod/jei/version/latest?version=1.22&loader=fabric
> fix(frontend): Properly handle empty version list on `version/latest`

- apps/frontend/src/pages/[type]/[id].vue
Adds an option to open the download modal with a preselected version and loader.
This is a QoL, while `https://modrinth.com/[type]/[id]/version/latest?version=<game_version>&loader=<loader>`  exists, the download modal has a much more intuitive and friendlier UI, showing the latest release, beta and alpha separate and offering a link to the Modrinth App
The link format is similar to the existing alternative 
`https://modrinth.com/[type]/[id]?version=<game_version>&loader=<loader>`
* `version` is the game version
* `loader` is the platform
Both are optional, with at least one being required to open the modal on page load
If version or loader are not a valid option for the project the modal will not open
> feat(frontend): Automatically open download modal when filter queries are present (on the main mod page)

- packages/ui/src/components/project/ProjectHeader.vue
- packages/ui/src/components/project/ProjectSidebarCompatibility.vue
Added an action to the tagitems that house categories and platforms. Not sure if this is the best approach, so happy to hear any feedback.
fixes #1960
> feat(frontend): project tags link to a search

- apps/frontend/src/pages/settings/billing/index.vue
show resubscribe button on servers when payment status is "failed" instead of just "cancelled"
> PY-53 Subscription Force Renewal Button

- apps/frontend/src/pages/search/[searchProjectType].vue
Fixes #3176
**Changes**:
- Sets the pagination to page one if the search is updated. This is the norm on most websites, and how users expect it to work.
**Technical changes:**
- Join `setPage` into `updateSearchResults`
- Take an optional page number in `updateSearchResults`
- Remove unused param to `updateSearchResults`
- Update `watch` to not double requests
- Use `scrollToTop` utility function
> fix(frontend): update search to reset to page 1

- apps/frontend/src/pages/[type]/[id]/version/[version].vue
This PR fixes a missing class on a button in the edit version page, it then ensures that the styling alings with the rest of the file containers.
> fix(frontend): add correct styling class to button

- .gitattributes
I noticed that the `.vscode` folder says LF endings should be used. However, I still regularily see CRLF. To fix this I've added a `.gitattributes` file which makes git convert endings to LF.
> feat: git attributes to enforce LF endings

- apps/frontend/src/composables/auth.js
- Fixes #3188
- Refactors if-else statement into ternary
- By default still redirects to dashboard
- Properly URL encode
> fix(frontend): finish auth when redirect URI is supplied

- apps/labrinth/src/util/cors.rs
- apps/labrinth/src/util/ratelimit.rs
Annoyed that this has been unresolved for so long, so made a hotfix-ish. Can probably make a more clean solution if `actix-cors` exposes a function to get the headers. Hoping for a swift review 🚀 
Fixes #2591
Fixes #2529
> fix(labrinth): cors headers on ratelimited

- apps/frontend/src/components/ui/servers/ContentVersionEditModal.vue
- apps/frontend/src/components/ui/servers/ContentVersionFilter.vue
- apps/frontend/src/components/ui/servers/TeleportDropdownMenu.vue
- apps/frontend/src/composables/pyroServers.ts
- apps/frontend/src/pages/servers/manage/[id]/content/index.vue
- packages/ui/src/components/base/Admonition.vue
- packages/ui/src/components/base/ManySelect.vue
- packages/ui/src/components/base/PopoutMenu.vue
- packages/ui/src/components/billing/PurchaseModal.vue
- packages/ui/src/components/index.ts
- New edit version modal
- Refreshed UI
- Allows users to select custom loader & version
- Displays selected version's loader and supported game versions
- Warns about modpack incompatibility
- Opens instantly instead of waiting for fetches
- Show alpha and beta releases
- Proper filtering of versions
- Handling of unsupported mods/plugins
- Error handling
- Fixed editing versions not working
- Changed references of mods in UI to plugins when using a plugin platform
- Fixed deleting, uploading and toggling plugins
- Fix some `pyroServers.ts` definitions
- Show name of external mods without file extension
- Make `.disabled` logic more reliable
> Server Content Tab Fixes & Improvements

- apps/frontend/src/pages/[type]/[id]/settings/license.vue
- packages/utils/index.ts
- packages/utils/licenses.ts
- packages/utils/types.ts
- Possibly fixes the confusion in #3017
- Add more understandable UI
- Field titles
- Field description
- Give fields enough width to be readable
- Rephrase some text
- Use more semantically correct elements
- Make paragraph not a label
- Fields no longer jump around
- Split SPDX-identifier and license name into two separate fields
- Fmt, sort imports
- Encourage license URL when selecting custom license
- Move to Vue composition API
- Move to TypeScript
- Move away from vue-multiselect to the dropdown component
- Use `formatProjectType` function for typesafety
- Remove unused form error highlighting code
- Creating typings for built-in licenses
- Move standard licenses to licenses.ts util
- There are other license-related utils I want to move there in the future
- Fix typo in Project …
> License UI redesign + composition API

- apps/frontend/src/pages/[type]/[id].vue
The MessageBanner padding that appears when a project is archived only has padding on the bottom and not the top. This means that there is no visual gap and it does follow the visual style of the rest of the website. I have fixed it.
> Fix MessageBanner padding

- apps/labrinth/Dockerfile
Currently, if Kubernetes sends SIGTERM to gracefully shutdown the pod, it will not do anything and wait for the graceful period seconds to forcefully kill the pod instead. dumb-init should fix this by handling signals for us.
Additionally, see https://github.com/Yelp/dumb-init#why-you-need-an-init-system
> Fix Labrinth container SIGTERM handling

- apps/labrinth/Cargo.toml
- apps/labrinth/src/lib.rs
- apps/labrinth/src/main.rs
- apps/labrinth/src/routes/mod.rs
Jemalloc doesn't compile on Windows (or at least on MSVC), so I made the dependency only active when not on MSVC.
> Fix Labrinth not compiling on Windows due to jemalloc dependency

- apps/frontend/src/pages/legal/cmp-info.vue
Stops the vue compiler from nagging you, and improves consistency with other tables. I put the headers into `<thead>` and body into `<tbody>`. Added in #3250. There is some discussion in vuejs/core#12088, but this seems like the easiest solution.
> refactor(web): create table in cmp-info according to spec

- apps/frontend/src/layouts/default.vue
Bigger footer padding
Fixes #3312
> fix(frontend): mobile navbar covers legal disclaimer

- packages/daedalus/src/minecraft.rs
- packages/daedalus/src/modded.rs
This allows daedelus to parse the `logging` field of a client.json.
> Add log config parsing support to daedelus

- .github/ISSUE_TEMPLATE/1-app-bug.yml
Where you can find Modrinth App version has changed place, and the about doesn't exist anymore
> Fix Modrinth App version GitHub issue text

- Cargo.lock
- apps/app-playground/Cargo.toml
- apps/app/Cargo.toml
- apps/daedalus_client/Cargo.toml
- apps/labrinth/Cargo.toml
- packages/app-lib/Cargo.toml
- packages/daedalus/Cargo.toml
This PR removes unused Rust dependencies across the monorepo, bringing down the total count of dependencies built with `cargo clippy --all-targets --workspace` on a Linux workstation from 1333 to 1286 (~5% improvement). This slightly speeds up build time and reduces storage requirements, which is key for quick CI and iteration times. I've detected these with [`cargo shear`](https://github.com/Boshen/cargo-shear).
All the packages in the monorepo build fine after these changes, confirming the removed dependencies were indeed unused.
> Remove unused Rust dependencies

- apps/frontend/src/pages/app.vue
These are fairly trivial changes to remove an unnecessary extra download link for the MacOS app disk image, as both links point to the same universal image anyway, which works on Macs with both Intel and ARM architectures. To make it clear to end users that such a disk image is indeed universal, the "Intel & Apple" wording is added. While at it, I've removed some seemingly dead code for Mac download artifact selection.
Looks fine on my end. Doesn't break anything I could see in the download page even when switching my user agent string to fake different OSes.
> Simplify Mac app download links

- apps/frontend/src/pages/moderation/review.vue
Moderation queue now uses "permalinks" when linking to projects, users, or organizations. It has the side effect of also fixing a bug where projects without versions would lead to a 404 page.
> Use permalinks in moderation queue page

- apps/daedalus_client/Dockerfile
- apps/labrinth/Dockerfile
This pull request addresses issues with the Docker images build process after PR #3588 landed, caused by Rust 2024 being a too new edition for the pinned Rust versions in some Dockerfiles.
> Docker build fixes

- apps/app-frontend/src/components/ui/world/modal/EditServerModal.vue
- apps/daedalus_client/src/error.rs
- apps/daedalus_client/src/util.rs
- packages/app-lib/.sqlx/query-1a979fbc58be7dde562b6f7c8fdcf9a4fc5a9817f4831c66bd56f2f4d0a00f82.json
- packages/app-lib/src/state/attached_world_data.rs
- packages/app-lib/src/state/fs_watcher.rs
This deletes the attached world data when a world is deleted. Also makes an enum smaller in order to make Clippy happy.
> Fix to attached world data

- apps/frontend/src/pages/news/changelog/[product]/[date].vue
- packages/ui/src/components/base/Timeline.vue
Removes the margin top negation and the margin top from the changelog entry as they just cancelled out each other and also caused the timeline div to overlap the "View full changelog" link making it impossible to click it,
> fix: changelog margins overlapping link

- apps/labrinth/.sqlx/query-5f75c0c48083de27f853ee877aac070567fd2ed2be4a9a038821b790dd7cb763.json
- apps/labrinth/src/database/models/project_item.rs
Four years ago, I created issue modrinth/labrinth#200. Today, while it adorns a different name (modrinth/code#2766), the issue remains the same. In celebration of Modrinth's oldest bug report, here is a fix.
Instead of having a separate `updated` field, it simply pulls the publish date of the most recent version. This should also allow the `updated` column on the `mods` table to be dropped at a later date, but I would rather get confirmation that it works before we go ahead with losing that data.
Fixes #2766
> Fix `updated` field including deleted versions

- apps/docs/src/content/docs/contributing/labrinth.md
- apps/labrinth/src/routes/internal/flows.rs
- docker-compose.yml
This pull request tweaks the Labrinth documentation to mention the new SMTP variables, the `dummy_data.sql` as inspiration on how to seed a new database, and point towards potential Redis caching woes that may happen during development. Similarly, short-circuiting logic is added to skip Sendy signups when no Sendy API details are set up, easing deployment on development environments. Finally, the `docker-compose.yml` file had its deprecated version declaration removed, getting rid of warnings I got when doing `docker compose up`.
> Minor Labrinth documentation and missing Sendy configuration handling tweaks

- apps/labrinth/src/routes/v3/analytics_get.rs
This pull request changes `resolution_minutes` in the `analytics_get` module to be a `NonZeroU32`, which prevents a division by zero panic seen on production deployments of Labrinth. As far as I can tell, only specially crafted requests may pass a zero value in this field.
> fix(labrinth): prevent division by zero panic on analytics routes

- apps/labrinth/src/routes/internal/billing.rs
I haven't tested this fix locally due to the complexity of setting up a proper environment, with working billing. However, a quick deployment to the staging environment should confirm whether these changes resolve the issue with subscription interval updates from the frontend not being applied in the database.
While I was at it, I also added two missing countries (one of them is mine!) to the hardcoded list of preferred currencies by country, which comes in handy if we end up doing regional (i.e., not USD-only) pricing at some point.
> fix(labrinth): tentative billing period update fix

- .github/ISSUE_TEMPLATE/1-app-bug.yml
- .github/ISSUE_TEMPLATE/2-web-bug.yml
- .github/ISSUE_TEMPLATE/3-api-bug.yml
- .github/ISSUE_TEMPLATE/4-feature-request.yml
When an issue has been already handled by our part, and thus gets closed, but affects many users and the fix takes a while to be rolled out, it usually happens that those who notice the matter later on don't realize previous reports already exist and end up creating duplicate issues.
Let's try to improve a little bit on that by not filtering out closed issues in the links for checking whether the same issue was already reported. This should make it more obvious to users who follow the link whether an issue for their problem already exists.
> docs(issue template): do not skip closed issues in link to existing issues

- apps/app-frontend/src/components/ui/world/modal/EditSingleplayerWorldModal.vue
This PR ensures that the `removeIcon` state inside the edit singleplayer world modal is reset correctly after closing (showing) the modal.
Previously it's state was not reset.
https://github.com/user-attachments/assets/2ede1a69-c41c-4ad5-8e00-88f1954fd46e
https://github.com/user-attachments/assets/a2e86daf-90f6-47bd-aca9-274d71849e60
> fix: reset reset-icon state value correctly in edit world modal

- apps/labrinth/src/auth/oauth/mod.rs
- apps/labrinth/src/auth/validate.rs
- apps/labrinth/src/routes/analytics.rs
- apps/labrinth/src/routes/internal/billing.rs
- apps/labrinth/src/routes/internal/flows.rs
- apps/labrinth/src/routes/internal/gdpr.rs
- apps/labrinth/src/routes/internal/moderation.rs
- apps/labrinth/src/routes/internal/pats.rs
- apps/labrinth/src/routes/internal/session.rs
- apps/labrinth/src/routes/maven.rs
- apps/labrinth/src/routes/updates.rs
- apps/labrinth/src/routes/v3/analytics_get.rs
- apps/labrinth/src/routes/v3/collections.rs
- apps/labrinth/src/routes/v3/friends.rs
- apps/labrinth/src/routes/v3/images.rs
- apps/labrinth/src/routes/v3/notifications.rs
- apps/labrinth/src/routes/v3/oauth_clients.rs
- apps/labrinth/src/routes/v3/organizations.rs
- apps/labrinth/src/routes/v3/payouts.rs
- apps/labrinth/src/routes/v3/project_creation.rs
- apps/labrinth/src/routes/v3/projects.rs
- apps/labrinth/src/routes/v3/reports.rs
- apps/labrinth/src/routes/v3/teams.rs
- apps/labrinth/src/routes/v3/threads.rs
- apps/labrinth/src/routes/v3/users.rs
- apps/labrinth/src/routes/v3/version_creation.rs
- apps/labrinth/src/routes/v3/version_file.rs
- apps/labrinth/src/routes/v3/versions.rs
This makes `get_user_from_headers` (and the similar function `check_is_moderator_from_headers`) take in a single `Scopes` parameter as a bitflag, rather than an `Option<&[Scopes]>`. This improves the performance and ergonomics of these functions.
> Improve `get_user_from_headers` signature

- Cargo.lock
- Cargo.toml
- `async-compression` 0.4.23 → 0.4.24
- `bitflags` 2.9.0 → 2.9.1
- `clap` 4.5.38 → 4.5.40
- `clickhouse` 0.13.2 → 0.13.3
- `flate2` 1.1.1 → 1.1.2
- `hyper-util` 0.1.11 → 0.1.14
- `lettre` 0.11.16 → 0.11.17
- `reqwest` 0.12.15 → 0.12.19
- `serde-xml-rs` 0.8.0 → 0.8.1
- `sqlx` 0.8.5 → 0.8.6
- `sysinfo` 0.35.1 → 0.35.2
- `tauri-plugin-deep-link` 2.2.1 → 2.3.0
- `tauri-plugin-dialog` 2.2.1 → 2.2.2
- `tauri-plugin-opener` 2.2.6 → 2.2.7
- `tauri-plugin-single-instance` 2.2.3 → 2.2.4
- `tokio` 1.45.0 → 1.45.1
- `uuid` 1.16.0 → 1.17.0
- `zip` 3.0.0 → 4.0.0
Additionally, I have included a note that `redis` cannot be updated to 0.32 until `deadpool-redis` has updated to it.
> Update some dependencies

- apps/app-frontend/src/components/ui/world/WorldItem.vue
- apps/app-frontend/src/pages/instance/Worlds.vue
This PR fixes the mentioned issue, by first seeing that the instance-path passed to the `showWorldInFolder` was missing, when accessing the `WorldItem` under an instance. 
1. Attempt was to just pass `:instance-path` to the `WorldItem` from the `Worlds` instance page, however that resulted in the action menu being wrong.
2. So final fix was to emit an event, which takes the singleplayer world to avoid having the check outside, which passes the instance path and the world path to the `showWorldInFolder` method.
https://github.com/user-attachments/assets/449454fa-e1eb-464b-9afe-b90dfbaadde6
closes: #3699
> fix: undefined instance path by using emitted event instead when opening world folder

- Cargo.lock
- apps/app-frontend/src/components/ui/instance_settings/HooksSettings.vue
- packages/app-lib/Cargo.toml
- packages/app-lib/src/api/profile/mod.rs
- packages/app-lib/src/launcher/mod.rs
- packages/app-lib/src/state/settings.rs
- packages/app-lib/src/util/mod.rs
This PR fixes the cleanup of per-instance launch hook overrides by bundling together several related, though technically distinct, smaller fixes:
- The `HookSettings` frontend page previously couldn't clear per-instance launch hooks because it failed to instruct the backend to clear the stored hook strings when no hooks were explicitly overridden. The frontend now correctly instructs the backend to clear the hooks in such cases.
- The backend incorrectly treated a `Some("")` launch hook as valid for launching Minecraft, even though it clearly isn't. It now correctly interprets `Some("")`, which may be read from the app state database for instances affected by issue #3730, as equivalent to `None`.
- During (de)serialization of launch hook structs to the frontend, the backend also …
> fix(app): make per-instance launch hooks clearable

- .github/workflows/turbo-ci.yml
- apps/app/turbo.jsonc
- docker-compose.yml
- package.json
- turbo.jsonc
This PR builds on #3776 by merging the separate lint and test steps in the CI workflow into a single "lint and test" step, which instructs Turborepo to run both tasks across all packages. The main benefit of this approach is that Turborepo can better parallelize the task execution graph (for instance, it can test the Rust app-lib while the app frontend is being linted), which potentially improves runtime (even though GitHub Actions runners have few CPU cores, so the effects won't probably be very significant).
Additionally, I've addressed a source of intermittent CI failures caused by database migrations being attempted before the database was fully initialized by adding health checks to the Compose file, and configuring the CI workflow to wait until those checks pass.
> Small CI flakiness fix and performance tweak

- apps/frontend/.env.local
- apps/labrinth/.env.local
Labrinth's `.env.local` file is configured to use a local filesystem storage backend for CDN content, storing CDN files (namely, user and project icons, and project versions) under `MOCK_FILE_PATH`. However, the `CDN_URL` in that file currently points to the staging environment CDN, which local deployments can't interact with. As a result, CDN-backed features are nonfunctional in local environments.
This PR addresses the issue by updating `CDN_URL` to use a proper file URL prefix pointing to the `MOCK_FILE_PATH` directory, thereby restoring the proper functioning of those features in local setups.
However, it's important to note that, for security reasons, most web browsers restrict HTTP origins from accessing file URLs. As such, this solution isn't sufficient out of the box to get the …
> fix(labrinth): use a proper `CDN_URL` for local deployments

- apps/frontend/src/pages/settings/billing/index.vue
When a payment for a subscription fails, we continue to try to re-attempt retrieving payment for 30 days.
Sometimes making it fail is an intentional choice on the user's part (e.g. Privacy.com card) or other times the user just doesn't want their subscription anymore after it fails.
This PR allows users with a failed payment to simply cancel instead of waiting for the 30-day timer to set in.
> Allow failed subscriptions to be cancelled

- apps/labrinth/src/util/routes.rs
- apps/labrinth/src/validate/datapack.rs
- apps/labrinth/src/validate/mod.rs
- apps/labrinth/src/validate/resourcepack.rs
- apps/labrinth/src/validate/shader.rs
As described in #2844, protected resource and data packs currently fail Labrinth's version file validation step because they cannot be reliably opened as ZIP archives by most ZIP libraries.
This is an intentional consequence of pack protection schemes, where the only invariant that has to be upheld is that game can load them just fine. Like other technical protection measures, these schemes can be used for both legitimate and malicious purposes, and Labrinth is not in a position to judge the intent. So, given Modrinth's largely neutral stance on the types of content allowed on the platform, it seems inappropriate to reject protected packs at this validation stage. (For reference, the linked issue describes a legitimate use case for such protection.)
This PR addresses the issue by …
> feat(labrinth): allow protected resource and data packs to pass validation

- apps/frontend/src/components/ui/ModerationChecklist.vue
Fixes indentation in the "Insufficient gallery images" moderation checklist message.
> fix: Insufficient gallery images moderation message indentation

- apps/app/Cargo.toml
- packages/app-lib/Cargo.toml
Currently, when attempting to compile or lint `packages/app-lib` directly, it fails due to requiring a `tauri` feature that is only enabled in `apps/app`. This PR adds this feature directly to `packages/app-lib`. It also removes it from `apps/app`, where it was unused.
> Fix direct lint of `packages/app-lib`

- .cargo/config.toml
```
[target.'cfg(windows)']
rustflags = ["-C", "link-args=/STACK:16777220"]
```
This will overwrite the flags ["--cfg", "tokio_unstable"] and cause panic.
> Update config.toml to fix the panic on windows

- packages/app-lib/java/build.gradle.kts
Spotless requires at least Java 11 to run. This updates Gradle to use Java 11, using `--release 8` to retain Java 8 compatibility.
> Update Java to 11 with `--release 8`

- Cargo.lock
- Cargo.toml
- apps/daedalus_client/Dockerfile
- apps/labrinth/Dockerfile
- clippy.toml
- rust-toolchain.toml
This PR makes the following dependency updates:
- Rust 1.87.0 → 1.88.0
- `async-compression` 0.4.24 → 0.4.25
- `reqwest` 0.12.19 → 0.12.20
- `rust_decimal` 1.37.1 → 1.37.2
- `sentry` 0.38.1 → 0.41.0
- `sentry-actix` 0.38.1 → 0.41.1
- `serde_with` 3.12.0 → 3.13.0
- `tauri` 2.5.1 → 2.6.1
- `tauri-build` 2.2.0 → 2.3.0
- `tauri-plugin-deep-link` 2.3.0 → 2.4.0
- `tauri-plugin-dialog` 2.2.2 → 2.3.0
- `tauri-plugin-opener` 2.2.7 → 2.4.0
- `tauri-plugin-os` 2.2.1 → 2.3.0
- `tauri-plugin-single-instance` 2.2.4 → 2.3.0
- `tauri-plugin-updater` 2.7.1 → 2.9.0
- `tauri-plugin-window-state` 2.2.2 → 2.3.0
- `wry` 0.51.2 → 0.52.1
- `zip` 4.0.0 → 4.2.0
> Rust dependency updates

- apps/labrinth/src/routes/internal/billing.rs
Some users elect to try to perform their upgrade immediately before their subscription renews. However, we throw an error whenever the proration charge is under 30 cents because we lose more money on fees than we gain by charging the customer. This PR changes charges so that the user's server will simply be provided a free upgrade instead of requiring them to wait until after their next renewal.
> Give free upgrades when billing period is near its end

- apps/frontend/src/pages/[type]/[id].vue
- apps/frontend/src/pages/collection/[id].vue
- apps/frontend/src/pages/organization/[id].vue
- apps/frontend/src/pages/search/[searchProjectType].vue
- apps/frontend/src/pages/user/[id].vue
Ads scripts seem to be leaking into the main environment (not user-level ad code, just from the ads platforms), which repeatedly causes parts of the site to break, especially for creators trying to upload their mods. Since site revenue is such a small fraction of the site's ad revenue, we're disabling ads for logged in users (mostly creators) to prevent issues for creators and fix the bugs caused by ads.
> Disable ads for logged in users (web)

- apps/labrinth/src/auth/checks.rs
Originally changed in #3408 but didn't address the full issue.
> Fix empty collections being shown on user pages

- apps/app-frontend/src/pages/Browse.vue
When searching for content in the Modrinth App, users may update the search query at any time by modifying the search text or other filters. Any of these actions can reduce the number of result pages returned, which may entail the current page number exceeding the available page range, causing the UI to display an invalid, empty page.
This PR addresses the issue by clamping the current page to be at most equal to the total page count whenever search results are refreshed. This ensures users always see the closest valid page to the one they were previously viewing.
I think it's worth pointing out that currently the app only uses the related `useSearch` function in the `Browse.vue` view. As such, I considered deeper architectural changes to the `currentPage` property out of scope: broader …
> fix(app-frontend): clamp current page in searches to the max possible

- packages/app-lib/java/src/main/java/com/modrinth/theseus/MinecraftLaunch.java
- packages/app-lib/src/launcher/mod.rs
As of the latest update, older Forge versions would fail to launch due to the launch wrapper being unable to access the main class's module. This bypasses that by forcing the main method to be accessible with accessibility checks.
Fixes #3910
> Fix launching older Forge versions

- .github/workflows/theseus-build.yml
- .github/workflows/theseus-release.yml
- Cargo.lock
- apps/app-frontend/package.json
- apps/app/Cargo.toml
- apps/app/tauri.conf.json
- packages/app-lib/Cargo.toml
This PR introduces several long-overdue improvements to finally achieve a complete continuous delivery setup for the Modrinth App. With these changes, nearly every part of the application's build and release lifecycle is automated, requiring minimal human intervention only to just trigger a release publish:
- The `theseus-release.yml` workflow has been renamed to `theseus-build.yml` to more accurately reflect its purpose: building application artifacts without releasing them to all users.
- App packages now include a placeholder version number, `1.0.0-local`, which is automatically replaced during the `theseus-build.yml` workflow with a proper version number based on the version tag or commit hash. Say goodbye to the tedious and error-prone task of manually updating version numbers! 🎉
- …
> ci: revamp app build workflow, introduce a new one for release deployment

- packages/app-lib/java/src/main/java/com/modrinth/theseus/MinecraftLaunch.java
I don't know of any mod loaders where this would be the case, but I think it's better to be safe than sorry.
> Fix MinecraftLaunch failing in the case of a package-private main class on Java 8

- .github/workflows/theseus-build.yml
- .github/workflows/theseus-release.yml
This PR refines the new Theseus build and release GitHub Actions workflows with the following improvements:
- The build workflow now excludes non-bundle work files generated by Tauri from the uploaded artifacts. This reduces artifact size and prevents unnecessary uploads to our S3-compatible bucket, saving on write operations and storage.
- The release workflow now correctly constructs URLs for RPM packages, fixing a typo (thanks to @Prospector for catching such a sneaky typo!).
- App builds triggered by non-tag pushes now use shorter, more user-friendly version strings. Previously, these strings included the full commit hash, which made them too long to display properly in the app's "About" screen. The version string is now generated using `git describe`, which combines the latest …
> ci(theseus): assorted tweaks and fixes

- apps/app-frontend/src/pages/instance/Logs.vue
This increases logs card's height to make it look more better, since right now I think it looks squished, I believe this change is also going to make logs easier to read in the app, screenshots below show before/after the change.
> feat(app): increase logs card height

- apps/frontend/src/locales/en-US/index.json
- packages/ui/src/components/billing/ServersPurchase1Region.vue
- packages/ui/src/locales/en-US/index.json
- packages/ui/src/utils/regions.ts
- Added eu-cov support, displayed as "Western Europe"
- Changed eu-lim to display as "Central Europe" instead of just "Europe"
- Changed eu-lim location to use flag of Germany
> Add coventry europe region support

- .github/workflows/turbo-ci.yml
It's easy to forget to run `pnpm intl:extract` after adding translations. This PR makes the CI fail if the default translation files are outdated (i.e. if `pnpm intl:extract` has not been run).
> Verify that `intl:extract` has been run

- apps/frontend/src/pages/[type]/[id]/gallery.vue
> fix(web): prevent gallery item description from overflowing

- apps/labrinth/src/auth/mod.rs
- apps/labrinth/src/routes/internal/flows.rs
Fixes #1485
Also fixes an issue where email_verified was being set to true regardless of whether the oauth provider provides an email (thus indicating that a null email is verified)
> Improve errors when email is already in use

- apps/labrinth/.sqlx/query-cf020daa52a1316e5f60d197196b880b72c0b2a576e470d9fd7182558103d055.json
- apps/labrinth/src/database/models/charge_item.rs
This allows people to cancel failed payments, currently it fails with error "There is no open charge for this subscription"
> Count failed payments as "open" charges

- .cargo/config.toml
The latest version of MSVC fails when linking labrinth, making now a perfect opportunity to switch over to the `rust-lld` linker instead.
> Use `rust-lld` linker on MSVC Windows

- .github/workflows/daedalus-docker.yml
- .github/workflows/labrinth-docker.yml
- apps/daedalus_client/Dockerfile
- apps/labrinth/Dockerfile
These changes improve the performance of our Docker image building process by enabling the reuse of cached results from previous runs in two ways:
- The Cargo target and source checkout directories are now set up as [cache mounts](https://docs.docker.com/build/cache/optimize/#use-cache-mounts). This allows Docker's BuildKit to reuse these directories even if the build layer cache is invalidated, which usually happens due to changes in source files copied via a previous `COPY` instruction.
- BuildKit caches are now stored externally as GitHub Actions cache artifacts, using [a dedicated storage backend](https://docs.docker.com/build/cache/backends/gha/). This enables cache reuse across workflow runs.
The first improvement can significantly enhance the developer experience during local …
> perf(docker): cache image builds through cache mounts and GHA cache

- apps/frontend/src/components/ui/thread/ConversationThread.vue
- apps/frontend/src/pages/[type]/[id].vue
- apps/frontend/src/pages/[type]/[id]/moderation.vue
By request of the moderation team. This would allow easier access
if, e.g., the moderators tell the author of a metadata problem they
need to correct.
> Re-enable the Moderation tab for projects that are approved

- apps/app-frontend/src/components/ui/ProjectCard.vue
Before, a project used to always show as "Optimization" if it was tagged as "Optimization". Now, it will only be forced to show as "Optimization" if it has "Optimization" as a *featured* tag. Additionally, featured tags are now always preferred over non-featured tags on the homepage.
Fixes DEV-219
> Fix most packs showing as "Optimization" on the app homepage

- apps/frontend/src/components/ui/moderation/checklist/ModerationChecklist.vue
- packages/assets/generated-icons.ts
- packages/assets/icons/toggle-left.svg
- packages/assets/icons/toggle-right.svg
Closes DEV-225
---
This PR adds a toggle button that allows moderators to switch between the advanced markdown editor and a simple plain text `textarea` input.
CodeMirror uses virtual scrolling for performance optimization, replacing off-screen content with `cm-gap` elements. However, this can cause rendering issues in certain contexts (such as floating containers), where lines become hidden even when they should be visible. 
It should be noted that this bug is rare, there's only been 2 recorded instances of it happening in the checklist.
Reference: https://discuss.codemirror.net/t/improve-scroll-performance-tradeoff/8825
- Added a toggle button in the moderation message editor (an actual `Toggle` was not used so that it can fit in with the `MarkdownEditor` formatting buttons.)
- …
> feat: add simple mode editor to the moderation checklist

- apps/frontend/src/pages/moderation/index.vue
- apps/frontend/src/pages/moderation/reports/index.vue
Closes DEV-215
---
This PR removes the usage of `localStorage` for persisting filter and "Sort By" dropdown states on the reports and moderation queue pages to resolve hydration mismatches.
The current implementation uses `localStorage` to persist filter and sort preferences across page reloads. However, this causes hydration issues where the server-side rendered content doesn't match the client-side state, similar to the issues we've experienced with the tremendous reward images not synchronizing properly with their corresponding cards.
The trade-off of losing filter persistence is acceptable given the stability improvements and the fact that these are administrative pages where consistent, predictable behavior is more important than convenience
> revert: dont use local storage for filters on moderation dash

- apps/frontend/src/pages/moderation/index.vue
Closes DEV-216
---
This PR changes the filtering logic in the moderation dashboard so that only the first project type in the `project_types` array is used. Generally the first project type in the array is the initial type, and anything after was done after the first version was uploaded (e.g. another version or the first version was edited) - there is a rare case when the first version triggers a mixed `project_types`, there is no way to work around that issue.
Ideally the backend should provide the actual type of the project, this could be addressed in the future changes to how the backend provides moderation queue/reports information, not a huge priority though, I couldn't find any projects in the queue in which the first version triggered multiple `project_types` to exist.
> fix: only check the first project type in filtering

- apps/labrinth/build.rs
The `build.rs` script currently contains this line:
```
println!("cargo::rerun-if-changed=.git/HEAD");
```
For the purpose of recomputing the `GIT_HASH` build-time environment variable if the current commit changes. However, `.git` is not present in the labrinth root—it's in the monorepo's root.
Because `labrinth/.git/HEAD` never exists, Cargo will detect a change and always rebuild the whole crate, even when nothing really changed.
Arguably that whole section of the build script could be removed or reworked as it doesn't even work with Docker builds/in prod.
> Fix cargo rebuilding labrinth even when no change was made

- .editorconfig
- docker-compose.yml
There is nothing interesting to describe here other than what's stated in the different commit titles. Giving containers a name in `docker-compose.yml` is useful for being able to referring to those by a well-known name in e.g. `.env` files, which will be leveraged in an incoming PR.
> Minor compose and editorconfig fixes

- .editorconfig
`cargo fmt` uses spaces for indentation, so this PR makes .editorconfig also use spaces so that every file doesn't require reformatting on every commit.
> Mark .editorconfig to use spaces for Rust code as the formatter does

- apps/frontend/src/components/ui/servers/FileItem.vue
- apps/frontend/src/pages/servers/manage/[id]/files.vue
This PR fixes the pagination issues on the files page of the server panel by relying on the backend's initial sorted file list rather than unessecarily sorting the files again for no reason.
Backend already sorts directories first, then files, with case-insensitive alphabetical ordering before paginating. Re-sorting on the client caused item order to shift across pages, making items appear missing until further scrolling.
> fix: remove client side sorting of files

- .gitignore
- .idea/gradle.xml
- .idea/modules.xml
- .idea/vcs.xml
This adds back `gradle.xml` and `vcs.xml` for hopefully even more successful importing and branch switching with IntelliJ. This PR also reformats the committed IDEA files with our `.editorconfig`.
> More IDEA files

- apps/frontend/src/components/ui/ProjectMemberHeader.vue
- apps/frontend/src/components/ui/moderation/ModerationProjectNags.vue
- apps/frontend/src/locales/en-US/index.json
Needs testing to see if it actually gives perf improvements for the moderators that are encountering issues.
> refactor: move nags out of main project member header for perf

- apps/frontend/src/components/ui/moderation/ModerationDelphiReportCard.vue
- apps/frontend/src/components/ui/moderation/ModerationReportCard.vue
Previously, clicking the view button of a report of a version would lead to a 404 due to a typo in the returned versionUrl.  
This fixes that by directing to project/version/id.
> fix: reports of a version provide a broken link

- apps/frontend/src/pages/[type]/[id]/gallery.vue
- apps/labrinth/src/routes/v3/project_creation.rs
- apps/labrinth/src/routes/v3/projects.rs
This reconciles a couple of differences between the frontend and backend regarding gallery image uploads.
- Frontend: The frontend thought that the limit should be 500 MiB for gallery images. This is obviously not right. It has been updated to 5 MiB.
- Backend: The backend has been rejecting anything between 2 MiB and 5 MiB, but this is inconsistent with prior usage, where the limit used to be 5 MiB. It has been updated to allow anything under 5 MiB.
Fixes #4291
> Fix larger gallery image uploading

- apps/labrinth/src/auth/templates/error.html
[As one Discord user vividly described it](https://discord.com/channels/734077874708938864/734077874708938867/1411512531914063963):
> Can someone from Modrinth Team push the devs to change the message on this error to redirect people to the official support page instead of this Discord Server? It's dumb that this error message tells them to join here, and then we all tell them to go to the support page.
>
> <details>
> <summary>Error screenshot</summary>
> <img width="413" height="706" alt="Modrinth auth callback error page screenshot" src="https://github.com/user-attachments/assets/b48551e8-33c2-446a-b25d-da69f588b885" />
> </details>
Therefore, this PR tweaks the wording of that error message to help prevent "dumb" situations for users, directing them to the support page instead. They …
> tweak(labrinth/auth): improve Modrinth auth callback error message

- packages/utils/parse.ts
> Disable fuzzy links to prevent unintended linkage when referring to files or version numbers that may appear like domains or IP addresses

- apps/frontend/src/composables/auth.js
- apps/frontend/src/pages/auth/sign-in.vue
- apps/labrinth/.env.docker-compose
- apps/labrinth/.env.local
@triphora brought to my attention a support ticket where a user reported being unable to log in to their Modrinth account in the latest version of the Modrinth App when using an external SSO provider, GitHub, due to them being redirected to a non-existent web page.
While investigating, I discovered that the frontend code responsible for computing the redirect URL for SSO login providers was still returning the URL used by previous app versions, `https://launcher-files.modrinth.com`. However, newer app versions complete the login flow by receiving the auth token through a localhost URL. As a result, the authentication flow for SSO logins could not complete, leaving users stuck on an R2 bucket error page.
This PR updates the frontend logic so that redirect URLs for SSO logins are generated …
> fix(app): make Modrinth account SSO logins from the app work

- apps/labrinth/src/routes/analytics.rs
While testing the changes from https://github.com/modrinth/code/pull/4343, I noticed that local environment deployments failed to update project view analytics in Clickhouse at the request of a local frontend server, always returning an HTTP 400 error with an `invalid page view URL specified!` message.
Looking into the cause, I found that the analytics ingestion code relied on a list of allowed origins defined in the `CORS_ALLOWED_ORIGINS` environment variable for view URL filtering. However, this variable is not defined in any `.env` template in the repository, nor in any staging or production environment as far as I can tell. It's also not validated during Labrinth startup in the `check_env_vars` function. The only reason views were counted in production was due to special-case code …
> fix(labrinth): proper page view ingest URL origin filtering

- apps/labrinth/src/database/mod.rs
- apps/labrinth/src/database/postgres_database.rs
- apps/labrinth/src/lib.rs
- apps/labrinth/src/main.rs
- apps/labrinth/src/routes/v2/version_file.rs
- apps/labrinth/src/routes/v3/version_file.rs
- apps/labrinth/tests/common/database.rs
- apps/labrinth/tests/common/mod.rs
Introduces a new `ReadOnlyPgPool` type, configured by `READONLY_DATABASE_URL`, `READONLY_DATABASE_MIN_CONNECTIONS`, `READONLY_DATABASE_MAX_CONNECTIONS`. If `READONLY_DATABASE_URL` is missing, it defaults to using the existing `PgPool`.
> Support alternative read-replica PgPool

- .cargo/config.toml
- .github/workflows/turbo-ci.yml
- Cargo.toml
- apps/labrinth/src/database/models/version_item.rs
- apps/labrinth/src/routes/v2/version_creation.rs
- packages/app-lib/src/state/cache.rs
- rust-toolchain.toml
Cranelift has much faster incremental recompiles, which helps when iterating on labrinth features.
Warnings are currently denied in the root Cargo.toml, which is good for rigorous CI but is annoying when quickly prototyping features and you don't mind some dead code or unused imports. This PR keeps warnings as warnings, but passes `-Dwarnings` in the CI test run to fail on warnings there.
> Use Nightly + Cranelift for dev, only fail on warnings in CI

- apps/frontend/src/components/ui/NotificationItem.vue
- apps/frontend/src/pages/[type]/[id].vue
> fix(app): properly show all versions and notify loaders

- apps/frontend/src/pages/[type]/[id].vue
Introduces logic to conditionally show the "Show all versions" checkbox only when both release and non-release versions are present - and automatically shows all versions if there are only non-release versions present (continuation of #4395)
> fix: hide versions checkbox depending on what game versions are avail

- apps/frontend/src/components/ui/dashboard/CreatorTaxFormModal.vue
- apps/frontend/src/composables/avalara1099.ts
- apps/frontend/src/layouts/default.vue
- apps/frontend/src/locales/en-US/index.json
- apps/frontend/src/pages/dashboard/revenue/index.vue
- apps/frontend/src/pages/dashboard/revenue/withdraw.vue
This PR implements the base tax compliance features seperately from the new payouts page in #4204 - the following needs done for this to be deployed on Monday:
This PR will be reverted when #4204 is ready to merge, to prevent conflicts.
> feat: temporary tax compliance impl

- apps/frontend/src/components/ui/OrganizationCreateModal.vue
> Org disabled frontend

- apps/frontend/src/components/ui/OrganizationCreateModal.vue
- apps/labrinth/.env.local
- apps/labrinth/.sqlx/query-eb792d5033d7079fe3555593d8731f8853235275e4d5614636b5db524a4920d5.json
- apps/labrinth/src/auth/checks.rs
- apps/labrinth/src/models/v3/projects.rs
- apps/labrinth/src/routes/v3/organizations.rs
- apps/labrinth/src/routes/v3/teams.rs
- apps/labrinth/tests/scopes.rs
- apps/labrinth/tests/teams.rs
- packages/utils/changelog.ts
Bad actors have recently ramped up their abuse of the organization creation feature. This appears to be for SEO spam purposes, and it has become a problem to the point of having a significant impact on the Modrinth platform, forcing us to temporarily disable organization creation and take measures against it.
This PR is the first of those measures: it makes organizations not publicly visible until they fulfill a set of criteria that demonstrates they serve a legitimate purpose.
Because this PR makes spam organizations virtually useless, as they won't be publicly visible anymore, we expect malicious activities related to them to decrease significantly. For this reason, I've decided to re-enable the organization creation frontend as a part of it, minimizing disruption to legitimate users.
> feat(labrinth): hide orgs without a purpose, re-enable organization creation

- apps/labrinth/src/database/models/user_item.rs
Maybe this will work? I dunno but users are still saying they're getting errors deleting accs. In theory it shouldn't matter if the transaction all gets committed at the same time, though, right? I can't really test this so I would like someone to tell me whether this will actually make a difference.
> Fix user deletion with new notifications_deliveries table for real

- packages/app-lib/src/launcher/args.rs
- packages/app-lib/src/launcher/download.rs
- packages/app-lib/src/util/platform.rs
- packages/daedalus/src/minecraft.rs
PR #4270 modified the internal `fetch` function used by the application to download version artifacts in a way that 4xx HTTP errors also caused an abnormal return, instead of just 5xx errors. That was a good change, but it had the unintended side effect of exposing our faulty logic elsewhere of trying to download non-native JAR library artifacts when only native artifacts are appropriate, at least according to the PrismLauncher source code I've read. Such a download always returned a 404 error, but because such error was considered successful, a dummy library file was still created and things worked seemingly fine.
These changes bring the Modrinth App behavior in this regard more in line with PrismLauncher's, avoiding downloading non-native artifacts for dependencies that have native …
> fix(app): make MC <1.12.2 downloadable again
