Cargo.lock
theseus/Cargo.toml
theseus/src/modpack/manifest.rs
theseus/src/modpack/mod.rs
theseus/src/modpack/modrinth_api.rs
theseus/src/modpack/pack.rs

Fix my previous PR, some compiler errors popped up (somehow missed in my testing cycle) and export to zip by default.

Fix modpacks, compile to zip

---

Cargo.lock
theseus/Cargo.toml
theseus/examples/download-pack.rs
theseus/src/data/meta.rs
theseus/src/data/settings.rs
theseus/src/launcher/args.rs
theseus/src/launcher/download.rs
theseus/src/launcher/java.rs
theseus/src/launcher/mod.rs
theseus/src/launcher/rules.rs
theseus/src/lib.rs
theseus/src/modpack/manifest.rs
theseus/src/modpack/mod.rs
theseus/src/modpack/modrinth_api.rs
theseus/src/modpack/pack.rs
theseus/src/util.rs
theseus_cli/src/main.rs

It's really just a bunch of refactors.

Some more refactors

---

.gitignore
theseus/src/state/metadata.rs
theseus/src/state/profiles.rs
theseus_gui/src/routes/search/index.svelte

Minor change to support search into the Theseus GUI. Also added a few minor tweaks to Theseus such as comments and replacing a magic value with a constant.

Add search to GUI and minor changes to Theseus.

---

.cargo/config.toml
theseus/src/api/profile.rs
theseus/src/state/dirs.rs
theseus_gui/.gitignore
theseus_gui/dist/.gitignore
theseus_gui/src-tauri/Cargo.toml

- Fixes deadlock in profile adding from ui (in profile sync)
- Increases windows stack size for performance
- Adds dist so new cloneswon't have tauri error

Deadlock fixes

---

theseus_gui/src/store/search.js

Modifies how formattedOrFacets is constructed in order to prevent OR relationship between loaders and versions.

Resolves inaccurate OR relationship between loaders and versions.

---

theseus/src/launcher/mod.rs

- fixes window env-clearing issue, blocking ability to run processes on windows

Windows fix process env vars

---

theseus/src/api/pack.rs
theseus/src/api/profile.rs
theseus/src/api/profile_create.rs
theseus/src/launcher/download.rs
theseus/src/launcher/mod.rs
theseus_playground/src/main.rs

- Put some of the large async functionss into Box::pins to put their state machines on the heap

added box pins

---

theseus_gui/src/App.vue

Fixes home page collapsed mode issues

Fix homepage

---

theseus_gui/src/App.vue
theseus_gui/src/pages/Browse.vue

Rounded the corner of the router-view to improve UI continuity
from:
to:

Rounded corner to improve UI continuity

---

theseus_gui/src/pages/instance/Options.vue

This PR should fix #755 | #771

Fix categories duplicating

---

theseus/src/api/profile/mod.rs

disable disabled projects after update

---

theseus_gui/src-tauri/Cargo.toml

fixed typo

---

theseus/src/state/settings.rs
theseus_gui/src/App.vue
theseus_gui/src/pages/Settings.vue

native decorations toggle

---

theseus_gui/src/pages/instance/Options.vue

Previously didn't update until you leave and go back into the profile page

Update breadcrumbs on profile name update

---

Cargo.lock
theseus/Cargo.toml
theseus_cli/Cargo.toml
theseus_gui/package.json
theseus_gui/src-tauri/Cargo.toml
theseus_gui/src-tauri/tauri.conf.json
theseus_gui/src/components/ui/AccountsCard.vue

crafatar is unstable as hell :)
> ... so it is as battle-tested if not more so than mc-heads.
Closes #894

Bump version + revert to mc-heads.net

---

theseus_gui/src/store/theme.js

Will eventually need the new component from knossos to be ported, but this will suffice for now
Closes #240
Closes #934

Enable light mode and OLED mode as options

---

Cargo.lock
theseus/Cargo.toml
theseus/src/api/hydra/complete.rs
theseus/src/api/hydra/init.rs
theseus/src/api/hydra/refresh.rs
theseus/src/api/hydra/stages/bearer_token.rs
theseus/src/api/hydra/stages/mod.rs
theseus/src/api/hydra/stages/player_info.rs
theseus/src/api/hydra/stages/poll_response.rs
theseus/src/api/hydra/stages/xbl_signin.rs
theseus/src/api/profile/create.rs
theseus/src/launcher/auth.rs
theseus/src/launcher/mod.rs
theseus_cli/Cargo.toml
theseus_cli/src/subcommands/profile.rs
theseus_gui/package.json
theseus_gui/src-tauri/Cargo.toml
theseus_gui/src-tauri/tauri.conf.json
theseus_gui/src/components/ui/AccountsCard.vue

Fixes auth issues people are having in our server

Fix auth (finally)

---

theseus/src/api/pack/import/mod.rs
theseus/src/api/settings.rs
theseus/src/state/dirs.rs
theseus/src/util/io.rs
theseus_gui/src/pages/Settings.vue

- Fixes an issue with config shifts across drives
- Adds temp files while writing to disk

Config transfer

---

theseus_gui/src/pages/project/Versions.vue

This PR fixes the project versions page which is currently just crashing.
I believe this was introduced in #1103

fix: version page

---

Cargo.lock
theseus/Cargo.toml
theseus/src/state/minecraft_auth.rs

- **Further auth requests consistency fixes**
- **Enable deflate, gzip and brotli compression support**

Further auth requests consistency fixes

---

packages/utils/parse.ts

Resolves: https://github.com/modrinth/knossos/issues/362

feat: Improve iframe parameter handling 

---

apps/frontend/src/pages/[type]/[id]/settings/index.vue
apps/frontend/src/pages/[type]/[id]/settings/tags.vue
packages/assets/styles/classes.scss
packages/assets/styles/highlightjs.scss

fixes #1317 fixes #1318
- fixes border on text boxes
- fixes tags and setting visibility not displaying correctly
- fixes images not displaying flex

Fix styling issues caused by omorphia/tailwind

---

README.md
apps/frontend/README.md
packages/eslint-config-custom/README.md

- Rename `olympus` to `code`
- Fixed frontend dev command

fix: README fixes

---

apps/app-frontend/src/components/ui/ErrorModal.vue

https://discord.com/channels/1129467000381526156/1266023863750365307

fix(theseus): Error modal

---

.github/workflows/frontend-pages.yml
apps/frontend/nuxt.config.ts
apps/frontend/src/pages/app.vue
apps/frontend/src/pages/index.vue

Moving back to a cache here temporarily so we can disable the Cloudflare check on the index page and improve performance 
Also clears Cloudflare Pages cache on main push

Cache homepage projects in tags

---

apps/frontend/src/helpers/infer.js

Fixes #1337
Fixes #1341
Fixes #1376
I attempted to fix these issues in #1326, but it didn't really work (sorry :3). Now it's totally fixed!

fix(frontend): Correctly parse `neoforge.mods.toml`

---

apps/frontend/src/helpers/package.js
apps/frontend/src/pages/[type]/[id]/version/[version].vue

feat(frontend): Package datapack as NeoForge mod

---

.github/workflows/app-release.yml
Cargo.lock
apps/app-frontend/package.json
apps/app-frontend/src/components/ui/AddContentButton.vue
apps/app-frontend/src/pages/instance/Logs.vue
apps/app-frontend/src/pages/instance/Mods.vue
apps/app/Cargo.toml
packages/app-lib/Cargo.toml
pnpm-lock.yaml

Switch to RustLS

---

apps/frontend/src/layouts/default.vue
apps/frontend/src/pages/[type]/[id].vue
apps/frontend/src/pages/settings/billing/index.vue

fix: not being able to Follow/Save/Report projects

---

apps/app-frontend/src/helpers/utils.js
apps/app/src/api/utils.rs

Resolves https://discord.com/channels/1129467000381526156/1275081576262139924

fix(theseus): Correctly open/highlight folders

---

Cargo.lock
apps/app-frontend/src/App.vue
apps/app/Cargo.toml
apps/app/src/main.rs
packages/app-lib/src/api/profile/mod.rs

Tauri init messages ported from: https://github.com/modrinth/code/pull/1181 (thanks braw!)
Fixes MRPack file includes and window state not saving

Fix MRPACK export file include, add webview2 fail msg, fix window state

---

packages/ui/src/components/base/ManySelect.vue

fixes linting issues introduced in 77a0d8cc0389dd67483a482483fd080b15418f64 merged to main in 2dd8d5a11975a844d64e38167fd62bcb691db816. Why? Because when people merge main into their PR, it fails ci 😃

fix(ui): lint #2306

---

apps/app/gen/schemas/linux-schema.json
apps/app/tauri.conf.json
packages/app-lib/src/event/emit.rs

fix(theseus): Posthog scripts, focus app when opening deeplink, update linux-schema

---

.github/workflows/app-release.yml
.github/workflows/ci.yml
Cargo.lock
Cargo.toml
apps/app-frontend/package.json
apps/app-frontend/src/pages/Settings.vue
apps/app-frontend/src/pages/instance/Options.vue
apps/app-frontend/src/pages/project/Gallery.vue
apps/app-playground/Cargo.toml
apps/app/Cargo.toml
apps/app/README.md
apps/app/nsis/hooks.nsi
apps/app/package.json
apps/app/src/api/ads.rs
apps/app/tauri.conf.json
apps/frontend/src/pages/[type]/[id]/gallery.vue
apps/frontend/src/public/promo-frame.html
packages/app-lib/Cargo.toml
packages/app-lib/src/api/profile/mod.rs
packages/app-lib/src/state/cache.rs
packages/app-lib/src/state/profiles.rs
packages/app-lib/src/util/platform.rs
pnpm-lock.yaml

Fixes #2357 
Fixes #2350 
Fixes #2340 
Fixes #2361
Fixes bug where app database gets locked sometimes
Fixes #2366 (app now reboots ad window every 5 minutes to improve perf)
Fixes #2349
- Fixes app name being theseus_gui.exe
- Updates app install location to old install location + removes invalid installs
- Adds keybind support to launcher gallery (so esc and arrow keys work)
- Uses raw images on site + launcher when gallery images are expanded

0.8.5 fixes

---

packages/utils/parse.ts

This PR fixes an issue where video, audio, and picture tags did not get proxied properly.

Fix markdown images

---

apps/app/src/api/ads.rs
apps/frontend/src/composables/display-names.ts
apps/frontend/src/helpers/highlight.js
apps/frontend/src/pages/[type]/[id].vue
apps/frontend/src/pages/[type]/[id]/version/[version]-new.vue
apps/frontend/src/pages/auth/authorize.vue
apps/frontend/src/pages/auth/verify-email.vue
apps/frontend/src/pages/settings/account.vue
apps/frontend/src/pages/settings/applications.vue
apps/frontend/src/pages/settings/language.vue
apps/frontend/src/public/promo-frame.html
packages/utils/highlight.ts
packages/utils/index.d.ts
packages/utils/parse.ts

CI failures are making PRs look bad, but it's actually the upstream.

chore: run lint

---

apps/app-frontend/src/components/ui/ErrorModal.vue

There was a typo on line 233 of ErrorModal.vue. I just had this error when starting the app and noticed it, thought I'd fix it rq

typo in ErrorModal.vue

---

apps/app-frontend/src/components/ui/InstanceCreationModal.vue
apps/app-frontend/src/pages/instance/Mods.vue

fix(theseus): Files drag & drop

---

apps/frontend/src/pages/servers/index.vue

feat(servers): allow scrolling faq into view via hashes

---

apps/frontend/src/pages/servers/index.vue

on ios/safari, the chevron was still visible on the summary elements on the faq. this fixes that

fix(servers): hide webkit details marker for faq

---

apps/frontend/src/components/ui/charts/ChartDisplay.vue

fix(frontend): alt-text for flags

---

apps/frontend/src/pages/servers/index.vue

fixed a bug in my previous PR where faq things wouldnt open when you initially nav to the page w/ the hash

fix(servers): faqs not opening on nav

---

apps/frontend/src/pages/servers/index.vue

fix: remove plan selector

---

apps/frontend/src/components/ui/servers/PanelTerminal.vue

fixes various issues with the terminal, mainly:
- log heights in the terminal are now cached, so scrolling and using the scrollbar to drag should not cause jumping as we memoized the heights
- hints to the browser that this is a highly interactive element, so we should see less frame drops
- scroll to bottom button should now work more reliably as the value to scroll down is no longer hardcoded and uses the actual heights of the items
- other bug fixes and performance improvements

refactor(terminal): rewrite terminal virtualization

---

apps/frontend/src/pages/servers/manage/[id]/options/startup.vue

show all java versions toggle

---

apps/frontend/src/components/ui/servers/BackupCreateModal.vue
apps/frontend/src/pages/servers/manage/[id]/backups.vue

automatically refresh backups list while one is being created

Fixes MOD-160

---

apps/frontend/src/pages/servers/manage/[id].vue
apps/frontend/src/pages/servers/manage/[id]/index.vue
apps/frontend/src/types/servers.ts

expose oom_killed and exit_code on crash events when the error inspector cannot automatically determine an issue

Fixes MOD-163

---

apps/app/gen/schemas/linux-schema.json

Keeps bugging me in git. Asked if should be committed, see https://discord.com/channels/734077874708938864/848329986577399818/1302710819792093266.

fix(app): update linux-schema.json

---

packages/assets/styles/variables.scss

- Fixed experimental styles on OLED
- Darkened sidebar background on OLED

OLED fixes

---

apps/app-frontend/src/main.js
apps/frontend/package.json
apps/frontend/src/plugins/floating-vue.js
apps/frontend/src/plugins/tooltip.js
packages/assets/styles/classes.scss
packages/ui/package.json
packages/ui/src/components/base/PopoutMenu.vue
pnpm-lock.yaml

Temporarily remove ribbit theme from popouts due to prod deploy bug.

Fix popouts not working

---

Cargo.lock
Cargo.toml
apps/app-frontend/package.json
apps/app/Cargo.toml
apps/app/src/api/ads.rs
apps/app/tauri.conf.json
packages/app-lib/Cargo.toml
packages/ui/src/components/content/ContentListPanel.vue

Fix app builds not launching

---

packages/app-lib/src/api/logs.rs

fixes #2949 (Cant Delete Logs)

fix(app): change function call

---

apps/frontend/src/pages/servers/manage/[id]/options/loader.vue

allows users to clean install modpacks when switching versions rather than forcing them to clean install latest, then switch versions

Update modpack to latest and clean reinstall on platform page

---

apps/frontend/src/components/ui/servers/ServerListing.vue
apps/frontend/src/pages/servers/manage/[id].vue
apps/frontend/src/pages/servers/manage/index.vue

- Displays a new screen for servers that are being upgraded
- New status bar in ServerListing that shows suspension reasons/upgrade status

Handle server upgrades (suspensions) in frontend

---

apps/frontend/src/components/ui/servers/ServerListing.vue
apps/frontend/src/composables/pyroServers.ts
apps/frontend/src/pages/servers/manage/[id].vue

the condition that displayed whether a suspension was due to a billing issue vs upgrading/transferring was faulty. it is no longer faulty. this also handles the new "support" suspension reason

Fix server suspension statuses

---

apps/frontend/src/pages/admin/user_email.vue
apps/labrinth/.sqlx/query-68619337ef34b588af21a40e5a60b54ce3a1dad45fb50bbc24a3ea34d2506578.json
apps/labrinth/src/routes/v3/users.rs

Allow admins to view user email

---

apps/frontend/src/assets/styles/layout.scss
apps/frontend/src/components/ui/Collapsible.vue
apps/frontend/src/components/ui/ModerationChecklist.vue
apps/frontend/src/composables/featureFlags.ts
apps/frontend/src/pages/[type]/[id].vue

featuring the Ultimate Sidebar:tm:

Moderation checklist enhancements

---

apps/frontend/src/components/ui/servers/Globe.vue
apps/frontend/src/pages/servers/index.vue

Servers Marketing: Add Dallas location to globe, change copy to refer to states

---

apps/frontend/src/components/ui/ModerationChecklist.vue

Fixed proof form styling in checklist

---

apps/frontend/src/layouts/default.vue

Add minimum height to content to fix space below the footer

---

apps/frontend/src/layouts/default.vue
apps/frontend/src/locales/en-US/index.json

Closes MOD-95
Also adds careers link back (Closes MOD-93)

Move Minecraft brand disclaimer to bottom of footer

---

apps/docs/package.json
apps/docs/src/content.config.ts
apps/docs/src/content/config.ts
pnpm-lock.yaml

Update the docs to latest deps/pkgs, in particular, astro v5
Update guides
https://docs.astro.build/en/guides/upgrade-to/v5
https://github.com/withastro/starlight/releases/tag/%40astrojs/starlight%400.30.0
Working on localhost
Resolves #3150

chore: update docs deps/pkgs

---

apps/frontend/src/layouts/default.vue

Add random project easter egg

---

apps/app-frontend/src/components/ui/modal/ModalWrapper.vue
apps/frontend/src/layouts/default.vue
packages/ui/src/components/modal/Modal.vue
packages/ui/src/components/modal/NewModal.vue

- Don't use repeat keystroke field as it seems unreliable on some systems (Closes #3336)
- Nullcheck modal event functions (Resolves #3339 - hopefully)

Minor bugfixes

---

apps/frontend/src/components/ui/report/ReportInfo.vue
apps/frontend/src/pages/moderation/review.vue

- Segmented teams and orgs requests to prevent breakage with 800 team requests
- Handle the case of a report for a deleted user

Fix moderation-side issues

---

apps/frontend/src/pages/search/[searchProjectType].vue

- Fixed game version filter being applied when searching for modpacks to install on your server
- Fixed plugin loaders not being filled when browsing for plugins to add to server

Servers search fixes

---

apps/frontend/src/pages/[type]/[id]/version/[version].vue

Limit project version number to 32 chars

---

apps/frontend/src/layouts/default.vue
apps/frontend/src/pages/pizza/index.vue
packages/assets/styles/variables.scss
packages/ui/src/components/base/Avatar.vue

more improvements for our new product

more improvements

---

Cargo.lock
apps/labrinth/src/routes/internal/statuses.rs
packages/app-lib/Cargo.toml
packages/app-lib/src/api/logs.rs
packages/app-lib/src/launcher/mod.rs
packages/app-lib/src/state/process.rs
packages/ariadne/src/versions.rs

Uses STDOUT for the default live log in the launcher

Launcher logs refactor

---

apps/daedalus_client/src/forge.rs
apps/labrinth/src/models/v3/billing.rs
apps/labrinth/src/routes/v2/version_creation.rs
apps/labrinth/src/routes/v3/version_file.rs
packages/app-lib/src/api/pack/import/curseforge.rs
packages/app-lib/src/util/io.rs

A fairly trivial PR for getting rid of some Clippy lints that are making mandatory CI checks fail.

Fix Clippy lints

---

apps/frontend/src/components/ui/servers/notice/AssignNoticeModal.vue
apps/frontend/src/components/ui/servers/notice/NoticeDashboardItem.vue
apps/frontend/src/pages/admin/servers/notices.vue
apps/frontend/src/pages/servers/manage/[id].vue
packages/ui/src/components/base/ServerNotice.vue
packages/utils/types.ts

Notices fixes and support for titles

---

apps/frontend/src/pages/admin/billing/[id].vue
apps/labrinth/src/routes/internal/billing.rs

for very specific weird circumstances where a server gets stuck/etc; useful for support

Allow servers to be unprovisioned without issuing a refund

---

apps/frontend/src/components/ui/ModalCreation.vue
apps/frontend/src/components/ui/NotificationItem.vue
apps/frontend/src/components/ui/OrganizationCreateModal.vue
apps/frontend/src/pages/[type]/[id].vue
apps/frontend/src/pages/[type]/[id]/version/[version].vue
apps/frontend/src/pages/collection/[id].vue
apps/frontend/src/pages/dashboard/revenue/index.vue
apps/frontend/src/pages/dashboard/revenue/transfers.vue
apps/frontend/src/pages/dashboard/revenue/withdraw.vue
apps/frontend/src/pages/settings/account.vue
apps/frontend/src/pages/settings/sessions.vue

Hey!
I've encountered a cors error while trying to add a new project, so it made me dig into it, found out it was an issue in some other places where they expect err.data to be defined, this pr is a fix to it keeping consistent with other places that use $notify.

fix(apps/frontend): error data can be undefined

---

apps/labrinth/src/util/captcha.rs

One notable but undocumented pain point when setting up a local Labrinth instance for development is that user registration through the UI doesn't work. A key reason for this is the requirement for hCaptcha verification, which isn't functional in local environments.
This straightforward PR resolves the issue by making Labrinth bypass hCaptcha verification when a valid hCaptcha secret isn't configured. As a result, user registration becomes functional in local deployments, without any impact on properly configured production or staging deployments.

Disable Labrinth hCaptcha verification when secret is unset

---

apps/frontend/src/pages/servers/index.vue

Clarify that Modrinth Servers prices are in USD

---

apps/frontend/src/pages/settings/billing/index.vue

If this were in place, I could have avoided about 40 different support tickets today

Improve wording about unprovisioned servers

---

apps/labrinth/migrations/20240115052708_base62-helper-functions.sql

Brought over from modrinth/labrinth#862

Add helpful functions for interacting with db manually

---

apps/frontend/src/composables/country.js
apps/frontend/src/composables/country.ts

Closes: #2263
Should also fix localized pricing on billing+modrinth servers page as well if the user doesn't directly access the page using a full page reload/refresh.

fix: country composable not working due to nuxt routing

---

apps/frontend/src/components/ui/ModerationChecklist.vue

Adds more checklist messages:
- Minecraft title
- Title similarities
- No English summary
- Insufficient gallery images

feat(moderation): Add more checklist messages

---

Cargo.lock
Cargo.toml
apps/labrinth/Cargo.toml
apps/labrinth/src/routes/v2/users.rs
apps/labrinth/src/routes/v3/users.rs
apps/labrinth/src/util/validate.rs

These changes fix #3663, and another unintended regression noticed after PR #3655 was merged.

PR 3655 regression fixes

---

apps/labrinth/src/models/v3/billing.rs
apps/labrinth/src/routes/internal/billing.rs

This quick and small PR introduces quarterly billing subscription support to Labrinth.

feat(labrinth): quarterly billing support

---

apps/frontend/src/composables/image-upload.ts

Modified the wording to let the user know the limit
PS: 1MB seems a bit low? something around the 2.5MB would be lot nicer

frontend: Improve file too large error

---

apps/frontend/src/pages/search/[searchProjectType].vue
apps/frontend/src/pages/servers/manage/[id]/options/index.vue

Fixed:
- installing modpacks from search
- setting subdomains

Servers hotfixes

---

apps/frontend/src/composables/featureFlags.ts
apps/labrinth/.sqlx/query-3a2ad5a5bd6c1c6e7cee467759633da038d74c6d41f55ae7f23fd1f04e577bdf.json
apps/labrinth/.sqlx/query-879bf4cc2e305c7e3e2456e2e0a0d910865d622f3add8ad6d99e9cddcc1d2f1a.json
apps/labrinth/src/routes/v3/payouts.rs

Fix platform revenue route

---

apps/frontend/src/components/ui/servers/ServerStats.vue

Makes things easier for support.

Force RAM to be listed by bytes instead of percent when in dev mode

---

apps/frontend/src/components/ui/servers/PlatformMrpackModal.vue
apps/frontend/src/composables/servers/modules/general.ts
packages/assets/icons/arrow-big-right-dash.svg
packages/assets/index.ts

[Screencast From 2025-06-29 16-47-31.webm](https://github.com/user-attachments/assets/ff2f8743-5011-4d77-beb2-ec7e4388fc10)

feat: mrpack upload progress in modal

---

apps/frontend/src/components/ui/servers/ContentVersionEditModal.vue
apps/frontend/src/components/ui/servers/ServerListing.vue
apps/frontend/src/pages/servers/manage/[id]/content/index.vue
apps/frontend/src/pages/servers/manage/[id]/options/network.vue
apps/frontend/src/pages/servers/manage/index.vue

I blame ~~@imb11~~ @Prospector

Fix some copy codes and avatars not showing up

---

apps/frontend/src/pages/app.vue

- Converted the page to typescript.
- Replaced `useAsyncData` with plain `useFetch` call, with type support & 5 minute interval caching.
- Detects platform on server side and then confirms it on the client, prevents hydration issues + a weird jump when the platform goes from undetected to detected.
- Removes unnecessary reactivity applied to the rows constant.
- Moved relevant logic into composables.
- Removed lazy loading to allow benefits of SSR.

refactor: cleanup & fix caching issues on /app page.

---

packages/moderation/data/keybinds.ts

collapse -> SHIFT + C instead of CTRL+SHIFT+C

fix: keybind for collapse

---

apps/frontend/src/components/ui/moderation/NewModerationChecklist.vue
packages/moderation/types/actions.ts
packages/moderation/utils.ts
packages/ui/src/components/base/DropdownSelect.vue

Closes DEV-162
Closes DEV-163
Closes DEV-164

Moderation Checklist Fixes

---

package.json
packages/moderation/data/messages/checklist-text/license/id.md
packages/moderation/data/messages/checklist-text/licensing.md
packages/moderation/data/messages/checklist-text/links/donation/donation.md
packages/moderation/data/messages/checklist-text/links/donation/donations.md
packages/moderation/data/stages/license.ts

Also, changes a button in the license step to use a conditional, preventing overlapping content from being generated.

fix text in license and links stages

---

packages/moderation/data/messages/reupload/identity_verification.md
packages/moderation/data/messages/status-alerts/tec/source_request-bins.md
packages/moderation/data/messages/status-alerts/tec/source_request-obfs.md
packages/moderation/data/stages/links.ts
packages/moderation/data/stages/reupload.ts
packages/moderation/data/stages/status-alerts.ts
packages/moderation/data/stages/versions.ts

Identity Verification button added to the reuploads stage.
Reupload stage options are now properly mutually exclusive.
Unaccessable links options label now only appears when it has valid options.
Source Code Request buttons (obvs and bins) added to the status alerts stage.

Add buttons for tec team, as well as other requested actions

---

packages/app-lib/src/api/pack/import/mmc.rs

Fix NeoForge instance importing from MultiMC/Prism

---

apps/labrinth/src/auth/checks.rs
apps/labrinth/src/models/v3/collections.rs
apps/labrinth/src/routes/v3/collections.rs
apps/labrinth/src/routes/v3/users.rs

Fix collection visibility once and for all

---

apps/frontend/src/components/ui/NewsletterButton.vue

As mentioned in the PR title, the newsletter subscription button on the blog page currently appears for a more or less brief period of time while the subscription status request is still being in flight. This is visually disruptive and may negatively affect Cumulative Layout Shift (CLS).
To improve this, let's wrap such an async status request in `useAsyncData`, and hold off on displaying the subscribe button until the request completes successfully and confirms that the user is not already subscribed to the newsletter. Therefore, once shown under these conditions, the button won't need to be hidden again.

fix(frontend): hide subscription button in blog before sub status is determined

---

packages/moderation/data/messages/side-types/inaccurate-modpack.md

Also replaces the Fabulously Optimized link with a permalink.

fix(moderation): Replace dead modpack link in side-types message

---

apps/app-frontend/src/pages/Browse.vue

This PR runs Prettier to format the source code in line with our CI checks, since commit https://github.com/modrinth/code/commit/8a3171d7c48add19497f9d9673ae28e045f4ff4a was merged into the main branch without passing those checks.

chore: fix CI failure due to unexpected formatting

---

apps/frontend/src/components/ui/servers/marketing/MedalPlanPromotion.vue

Not a perfect fix but it prevents it from being rubbish.
**Before:**
**After:**

fix: medal promotion on mobile

---

apps/frontend/src/pages/servers/index.vue

fix: dont auth on empty plan query

---

apps/frontend/src/pages/admin/billing/[id].vue

- Adds support for `medal` "product".
- Adds support for the new "expiring" state (introduced in #4121 afaik)

fix: medal support in admin billing

---

packages/app-lib/src/state/fs_watcher.rs

Instead of creating an empty servers.dat to watch, the app now non-recursively watches the profile's root directory.

Don't create an empty servers.dat on instance creation

---

apps/labrinth/src/routes/v3/payouts.rs

Title, plus fixes a bug in the compliance check

Add tax compliance form related fields to GET /payout 

---

apps/docs/public/openapi.yaml

Clarify date timestamps in search docs

---

apps/frontend/src/components/ui/NavTabs.vue
apps/frontend/src/pages/search/[searchProjectType].vue

Reset search when header button is clicked

---

apps/frontend/src/components/ui/ProjectCard.vue

Force summaries to wrap in search results

---

apps/frontend/src/pages/settings/billing/index.vue
apps/frontend/src/pages/settings/index.vue
packages/ui/src/components/settings/ThemeSelector.vue

Fixed a few icons in settings shrinking on mobile

---

apps/frontend/src/pages/[type]/[id]/settings/description.vue

mod -> project in description settings

---

apps/labrinth/.sqlx/query-10200da00caaa8f1c0976b9b705bf6d74a59bb62ee5da6dccffec99f36eddac7.json
apps/labrinth/.sqlx/query-6ef8402f0f0685acda118c024d82e31b1b235ab7c5ec00a86af4dfbe81342a58.json
apps/labrinth/.sqlx/query-81cfa59dafa8dac87a917a3ddda93d412a579ab17d9dad754e7d9e26d78e0e80.json
apps/labrinth/.sqlx/query-b27a1495f0a937e1bae944cfe6e46a4f702536816e5259c4aeec8b905b507473.json
apps/labrinth/.sqlx/query-b36457e1aa73b5517ca4f41e4144084a0aa996168d2660c13a1d4c9fc4594859.json
apps/labrinth/.sqlx/query-d51d96a9771ce1c3a2987e0790ef25bc55122c934c73418a97ee9cd81f56b251.json
apps/labrinth/migrations/20250914190749_affiliate_codes.sql
apps/labrinth/src/database/models/affiliate_code_item.rs
apps/labrinth/src/database/models/ids.rs
apps/labrinth/src/database/models/mod.rs
apps/labrinth/src/models/v3/affiliate_code.rs
apps/labrinth/src/models/v3/ids.rs
apps/labrinth/src/models/v3/mod.rs
apps/labrinth/src/routes/internal/affiliate.rs
apps/labrinth/src/routes/internal/mod.rs

Still need to check if the routes make sense, and frontend is happy with the given routes. Maybe `/_internal/affiliate` fetches affiliate user data as well as their ID? Or should the frontend be responsible?
Fixes DEV-255

Initial affiliate codes implementation

---

apps/app-frontend/package.json
apps/app-frontend/src/helpers/worlds.ts
pnpm-lock.yaml

I will continue maintaining this project, though updates may be slightly slower. 🙏❤️

Update MOTD Parser package

---

apps/labrinth/.sqlx/query-050e755134f6d1f09de805ae2cd0f7ca8f6efb96be9f070c43db7fd2049af2d2.json
apps/labrinth/src/database/models/charge_item.rs
apps/labrinth/src/queue/billing.rs
apps/labrinth/src/routes/internal/billing.rs
apps/labrinth/src/routes/internal/billing/payments.rs
apps/labrinth/src/util/anrok.rs

Also fixes an issue where charges with unresolvable addresses would be retried forever, and increases the number of transactions synchronized to Anrok per index

Link customer ID to Anrok transaction
